//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: bashi_club.proto

module Cmd {
	/**
	 * 通用结果返回
	 */
	export class BSClubResult {
		/**
		 * 返回码 1成功
		 */
		Code: number;
		/**
		 * 返回码描述
		 */
		Message: string;
		GetType(): string { return 'Cmd.BSClubResult'; }
	}
	/**
	 * 登录俱乐部
	 */
	export class BSClubLoginCmd_CS {
		/**
		 * 游戏账号ID
		 */
		OutAccountId: number;
		/**
		 * 游戏ID
		 */
		GameId: number;
		/**
		 * 昵称
		 */
		NickName: string;
		/**
		 * 头像地址
		 */
		HeadUrl: string;
		/**
		 * 登录数据
		 */
		Data: BSClubLoginCmd_CS.LoginData;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		/**
		 * 巴适平台登录专用
		 */
		BSPlatUid: number;
		/**
		 * 巴适平台登录专用
		 */
		BSPlatSession: string;
		GetType(): string { return 'Cmd.BSClubLoginCmd_CS'; }
	}
	export module BSClubLoginCmd_CS {
		export class LoginData {
			/**
			 * 俱乐部ID
			 */
			ClubId: number;
			/**
			 * 俱乐部名称
			 */
			ClubName: string;
			/**
			 * 俱乐部账号
			 */
			AccountId: number;
			/**
			 * 创建俱乐部跳转url
			 */
			CreateClubUrl: string;
			/**
			 * 管理俱乐部跳转url
			 */
			ManageClubUrl: string;
			/**
			 * 加入俱乐部金币阈值
			 */
			ThresholdValueIn: number;
			/**
			 * 退出俱乐部金币阈值
			 */
			ThresholdValueOut: number;
			GetType(): string { return 'Cmd.BSClubLoginCmd_CS.LoginData'; }
		}
	}
	/**
	 * 加入俱乐部
	 */
	export class BSClubJoinCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部ID
		 */
		ClubId: number;
		/**
		 * 俱乐部管理员UID
		 */
		OwnerId: number;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubJoinCmd_CS'; }
	}
	/**
	 * 退出俱乐部
	 */
	export class BSClubExitCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部ID
		 */
		ClubId: number;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubExitCmd_CS'; }
	}
	/**
	 * 俱乐部数据
	 */
	export class BSClubInfoCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部ID
		 */
		ClubId: number;
		/**
		 * 俱乐部数据
		 */
		Data: BSClubInfoCmd_CS.ClubInfo;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubInfoCmd_CS'; }
	}
	export module BSClubInfoCmd_CS {
		export class ActivityInfo {
			/**
			 * 活动Id
			 */
			Id: number;
			/**
			 * 活动标题
			 */
			Title: string;
			/**
			 * 活动内容
			 */
			Content: string;
			GetType(): string { return 'Cmd.BSClubInfoCmd_CS.ActivityInfo'; }
		}
	}
	export module BSClubInfoCmd_CS {
		export class ClubInfo {
			/**
			 * 俱乐部ID
			 */
			ClubId: number;
			/**
			 * 俱乐部名称
			 */
			ClubName: string;
			/**
			 * 俱乐部公告
			 */
			Notice: string;
			/**
			 * 管理员俱乐部账号
			 */
			OwnerId: number;
			/**
			 * 管理员昵称
			 */
			OwnerName: string;
			/**
			 * 是否为管理员
			 */
			IsOwner: boolean;
			/**
			 * 活动列表
			 */
			Activities: BSClubInfoCmd_CS.ActivityInfo[];
			/**
			 * 俱乐部是否可使用赠送功能，赠送|被赠送
			 */
			ClubCanTransfer: number;
			/**
			 * 自己是否可使用赠送功能，赠送|被赠送
			 */
			CanTransfer: number;
			/**
			 * 赠送金币最小值
			 */
			TransferAmountMin: number;
			/**
			 * 赠送金币最大值
			 */
			TransferAmountMax: number;
			GetType(): string { return 'Cmd.BSClubInfoCmd_CS.ClubInfo'; }
		}
	}
	/**
	 * 俱乐部成员列表
	 */
	export class BSClubMemberListCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部ID
		 */
		ClubId: number;
		/**
		 * 页索引
		 */
		PageIndex: number;
		/**
		 * 页容量
		 */
		PageSize: number;
		/**
		 * 成员列表数据
		 */
		Data: BSClubMemberListCmd_CS.MemberListData;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubMemberListCmd_CS'; }
	}
	export module BSClubMemberListCmd_CS {
		export class MemberInfo {
			/**
			 * 俱乐部账号
			 */
			AccountId: number;
			/**
			 * 是否为管理员
			 */
			IsOwner: boolean;
			/**
			 * 昵称
			 */
			NickName: string;
			/**
			 * 游戏账号ID
			 */
			OutAccountId: number;
			/**
			 * 是否可使用赠送功能，赠送|被赠送
			 */
			CanTransfer: number;
			GetType(): string { return 'Cmd.BSClubMemberListCmd_CS.MemberInfo'; }
		}
	}
	export module BSClubMemberListCmd_CS {
		export class MemberListData {
			/**
			 * 成员数量
			 */
			MaxCount: number;
			/**
			 * 成员数据列表
			 */
			Result: BSClubMemberListCmd_CS.MemberInfo[];
			GetType(): string { return 'Cmd.BSClubMemberListCmd_CS.MemberListData'; }
		}
	}
	/**
	 * 俱乐部成员查找
	 */
	export class BSClubMemberFindCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部ID
		 */
		ClubId: number;
		/**
		 * 查询游戏账号ID
		 */
		OutAccountId: number;
		/**
		 * 成员数据
		 */
		Data: BSClubMemberFindCmd_CS.MemberInfo;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubMemberFindCmd_CS'; }
	}
	export module BSClubMemberFindCmd_CS {
		export class MemberInfo {
			/**
			 * 俱乐部账号
			 */
			AccountId: number;
			/**
			 * 是否为管理员
			 */
			IsOwner: boolean;
			/**
			 * 昵称
			 */
			NickName: string;
			/**
			 * 游戏账号ID
			 */
			OutAccountId: number;
			GetType(): string { return 'Cmd.BSClubMemberFindCmd_CS.MemberInfo'; }
		}
	}
	/**
	 * 检查能否转账，平台返回处理过的结果
	 */
	export class BSClubCanTransferCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部账号
		 */
		ToAccountId: number;
		/**
		 * 金币数量
		 */
		GoldAmount: number;
		/**
		 * 回调数据
		 */
		Data: BSClubCanTransferCmd_CS.TransferData;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubCanTransferCmd_CS'; }
	}
	export module BSClubCanTransferCmd_CS {
		export class TransferData {
			/**
			 * 金币数量
			 */
			GoldAmount: number;
			GetType(): string { return 'Cmd.BSClubCanTransferCmd_CS.TransferData'; }
		}
	}
	/**
	 * 赠送金币
	 */
	export class BSClubGiftGoldCmd_CS {
		/**
		 * 赠送者uid
		 */
		uid: number;
		/**
		 * 金币数量
		 */
		chipsNum: number;
		/**
		 * 赠送者昵称
		 */
		nickName: string;
		GetType(): string { return 'Cmd.BSClubGiftGoldCmd_CS'; }
	}
	/**
	 * 使用礼券
	 */
	export class BSClubUseCouponCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 俱乐部ID
		 */
		ClubId: number;
		/**
		 * 礼券码
		 */
		CouponCode: string;
		/**
		 * 礼券数据
		 */
		Data: BSClubUseCouponCmd_CS.CouponData;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubUseCouponCmd_CS'; }
	}
	export module BSClubUseCouponCmd_CS {
		export class CouponData {
			/**
			 * 管理员游戏账号，0则为系统生成
			 */
			OwnerOutAccountId: number;
			/**
			 * 金币数量
			 */
			GoldAmount: number;
			GetType(): string { return 'Cmd.BSClubUseCouponCmd_CS.CouponData'; }
		}
	}
	/**
	 * 使用礼券回调
	 */
	export class BSClubUseCouponCallBackCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 礼券码
		 */
		CouponCode: string;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubUseCouponCallBackCmd_CS'; }
	}
	/**
	 * 创建俱乐部
	 */
	export class BSClubCreateCmd_CS {
		/**
		 * 登录url
		 */
		url: string;
		/**
		 * 登录token
		 */
		token: string;
		GetType(): string { return 'Cmd.BSClubCreateCmd_CS'; }
	}
	/**
	 * 管理俱乐部
	 */
	export class BSClubManageCmd_CS {
		/**
		 * 登录url
		 */
		url: string;
		/**
		 * 登录token
		 */
		token: string;
		GetType(): string { return 'Cmd.BSClubManageCmd_CS'; }
	}
	/**
	 * 使用点卡
	 */
	export class BSClubUseCardCmd_CS {
		/**
		 * 俱乐部账号
		 */
		AccountId: number;
		/**
		 * 点卡号
		 */
		CardNum: string;
		/**
		 * 点卡密码
		 */
		CardKey: string;
		/**
		 * 点卡数据
		 */
		Data: BSClubUseCardCmd_CS.CardData;
		/**
		 * 结果数据
		 */
		Result: BSClubResult;
		GetType(): string { return 'Cmd.BSClubUseCardCmd_CS'; }
	}
	export module BSClubUseCardCmd_CS {
		export class CardData {
			/**
			 * 金币数量
			 */
			GoldAmount: number;
			GetType(): string { return 'Cmd.BSClubUseCardCmd_CS.CardData'; }
		}
	}
}
