//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby_mini.proto
/// <reference path="common.ts" />

module Cmd {
	/**
	 * 下注类型枚举
	 */
	export enum LuckTurntableBetType {
		/**
		 * 正常下注
		 */
		LuckTurntableBetType_Normal = 1,
		/**
		 * 复投 重复上次下注
		 */
		LuckTurntableBetType_ReBet = 2
	}
	/**
	 * 玩家在线状态
	 */
	export enum LuckTurntableState {
		/**
		 * 准备阶段
		 */
		LuckTurntableState_Ready = 1,
		/**
		 * 下注阶段
		 */
		LuckTurntableState_Bet = 2,
		/**
		 * 转盘转动阶段
		 */
		LuckTurntableState_Run = 3,
		/**
		 * 开奖阶段
		 */
		LuckTurntableState_Open = 4,
		/**
		 * 控制阶段
		 */
		LuckTurntableState_Control = 5,
		/**
		 * 准备开奖阶段
		 */
		LuckTurntableState_Prepare = 6
	}
	/**
	 * 下注信息
	 */
	export class LuckTurntableBetInfo {
		/**
		 * 下注id
		 */
		id: number;
		/**
		 * 下注额度
		 */
		num: number;
		/**
		 * 赔率
		 */
		obbs: number;
		GetType(): string { return 'Cmd.LuckTurntableBetInfo'; }
	}
	/**
	 * 获取当前转盘信息信息
	 */
	export class RequestLuckTurntbaleInfo_C {
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 是否请求可下注信息 1表示需要请求，其他表示不需要
		 */
		requestBetInfo: number;
		GetType(): string { return 'Cmd.RequestLuckTurntbaleInfo_C'; }
	}
	/**
	 * 幸运转盘刷新
	 */
	export class UpdateLuckTurntableMiniCmd_S {
		/**
		 * LuckTurntableState
		 */
		state: number;
		/**
		 * 倒计时,秒
		 */
		leftSec: number;
		/**
		 * 期号
		 */
		curRoundId: number;
		/**
		 * 总下注情况
		 */
		allBet: LuckTurntableBetInfo;
		/**
		 * 我的总下注情况
		 */
		myBet: LuckTurntableBetItem[];
		/**
		 * 开奖情况
		 */
		openResult: LuckTurntableHistory;
		/**
		 * 可下注信息 id对应赔率
		 */
		betInfo: LuckTurntableBetInfo[];
		/**
		 * 总时间
		 */
		totalSec: number;
		/**
		 * 往期开奖情况
		 */
		openList: LuckTurntableHistory[];
		GetType(): string { return 'Cmd.UpdateLuckTurntableMiniCmd_S'; }
	}
	/**
	 * 幸运转盘下注
	 */
	export class BetLuckTurntableMiniCmd_CS {
		/**
		 * 下注详情
		 */
		betData: LuckTurntableBetItem;
		GetType(): string { return 'Cmd.BetLuckTurntableMiniCmd_CS'; }
	}
	/**
	 * 单次下注信息
	 */
	export class LuckTurntableBetItem {
		/**
		 * 下注id
		 */
		id: number;
		/**
		 * 下注额度
		 */
		num: number;
		/**
		 * 看情况,如果需要给其他人广播下注消息的话,就用,不填就表示自己下注
		 */
		uid: number;
		/**
		 * 下注类型
		 */
		betType: LuckTurntableBetType;
		/**
		 * 订单号
		 */
		orderId: number;
		/**
		 * 单门押注利润
		 */
		profit: number;
		GetType(): string { return 'Cmd.LuckTurntableBetItem'; }
	}
	/**
	 * 每期的总押注情况
	 */
	export class LuckTurntableBetHistoryData {
		/**
		 * 期号
		 */
		roundId: number;
		/**
		 * 下注详情
		 */
		betData: LuckTurntableBetItem[];
		/**
		 * 总投注数
		 */
		betNum: number;
		/**
		 * 自己在当次的利润
		 */
		profits: number;
		/**
		 * 中奖id
		 */
		id: number;
		GetType(): string { return 'Cmd.LuckTurntableBetHistoryData'; }
	}
	/**
	 * 下注信息
	 */
	export class LuckTurntableHistory {
		/**
		 * 中奖id
		 */
		id: number;
		/**
		 * 下注额度
		 */
		num: number;
		/**
		 * 期号
		 */
		roundId: number;
		/**
		 * 自己在当次的利润
		 */
		profits: number;
		GetType(): string { return 'Cmd.LuckTurntableHistory'; }
	}
	/**
	 * 请求幸运转盘路单
	 */
	export class HistoryLuckTurntableMiniCmd_C {
		GetType(): string { return 'Cmd.HistoryLuckTurntableMiniCmd_C'; }
	}
	/**
	 * 幸运转盘路单
	 */
	export class HistoryLuckTurntableMiniCmd_S {
		/**
		 * 路单
		 */
		list: LuckTurntableHistory[];
		GetType(): string { return 'Cmd.HistoryLuckTurntableMiniCmd_S'; }
	}
	/**
	 * 开奖结果返回
	 */
	export class OpenLuckTurnTableMiniCmd_S {
		/**
		 * 路单
		 */
		result: LuckTurntableHistory;
		GetType(): string { return 'Cmd.OpenLuckTurnTableMiniCmd_S'; }
	}
	/**
	 * 请求自己所有押注信息
	 */
	export class RequestBetHistoryCmd_C {
		/**
		 * 当前请求第几页
		 */
		curPage: number;
		GetType(): string { return 'Cmd.RequestBetHistoryCmd_C'; }
	}
	/**
	 * 请求自己所有历史押注信息
	 */
	export class ReturntBetHistoryCmd_S {
		/**
		 * 所有历史押注信息
		 */
		betData: LuckTurntableBetHistoryData[];
		/**
		 * 总页数
		 */
		totalPage: number;
		/**
		 * 当前是多少页
		 */
		curPage: number;
		GetType(): string { return 'Cmd.ReturntBetHistoryCmd_S'; }
	}
	export class UpdateSystemControlValue_CS {
		/**
		 * 系统分
		 */
		sysPoint: number;
		/**
		 * 吃分线
		 */
		eatPoint: number;
		/**
		 * 分线
		 */
		spitPoint: number;
		/**
		 * 当前系统分
		 */
		gainPoint: number;
		GetType(): string { return 'Cmd.UpdateSystemControlValue_CS'; }
	}
	/**
	 * 控制开奖
	 */
	export class SystemControlOpenLottery_C {
		/**
		 * 中奖Id
		 */
		lotteryId: number;
		GetType(): string { return 'Cmd.SystemControlOpenLottery_C'; }
	}
	/**
	 * 控制台后台
	 */
	export class UpdateSystemControlData_S {
		/**
		 * 结算数据
		 */
		settlelist: LuckTurntableBetHistoryData;
		/**
		 * 系统分（当前值）
		 */
		gainPoint: number;
		/**
		 * 总押注
		 */
		betChips: number;
		/**
		 * 最小赔付
		 */
		minChips: number;
		/**
		 * 最大赔付
		 */
		maxChips: number;
		GetType(): string { return 'Cmd.UpdateSystemControlData_S'; }
	}
}
