//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby_league.proto
/// <reference path="common.ts" />
/// <reference path="lobby_room.ts" />

module Cmd {
	/**
	 *  联盟相关协议--------------------------------------------------------------------------------------------
	 *  请求创建联盟
	 */
	export class CreateLeagueCmd_C {
		/**
		 * 联盟id,6位数
		 */
		leagueId: number;
		/**
		 * 联盟名称
		 */
		name: string;
		GetType(): string { return 'Cmd.CreateLeagueCmd_C'; }
	}
	/**
	 * 建联盟返回
	 */
	export class CreateLeagueCmd_S {
		/**
		 * 联盟id,6位数
		 */
		leagueId: number;
		/**
		 * 联盟名称
		 */
		name: string;
		GetType(): string { return 'Cmd.CreateLeagueCmd_S'; }
	}
	/**
	 * 修改联盟名称
	 */
	export class ChangeNameLeagueCmd_C {
		/**
		 * 联盟id,6位数
		 */
		leagueId: number;
		/**
		 * 联盟名称
		 */
		name: string;
		GetType(): string { return 'Cmd.ChangeNameLeagueCmd_C'; }
	}
	/**
	 * 请求我加入过的联盟
	 */
	export class RequestJoinedListLeagueCmd_C {
		/**
		 * 可以不填
		 */
		uid: number;
		GetType(): string { return 'Cmd.RequestJoinedListLeagueCmd_C'; }
	}
	/**
	 * 联盟摘要信息
	 */
	export class LeagueInfo {
		/**
		 * 联盟id
		 */
		id: number;
		/**
		 * 联盟名称
		 */
		name: string;
		/**
		 * 主人id
		 */
		uid: number;
		/**
		 * 主人头像
		 */
		headurl: string;
		/**
		 * 主人昵称
		 */
		nickname: string;
		GetType(): string { return 'Cmd.LeagueInfo'; }
	}
	/**
	 * 请求我加入过的联盟
	 */
	export class ReturnJoinedListLeagueCmd_S {
		list: LeagueInfo[];
		GetType(): string { return 'Cmd.ReturnJoinedListLeagueCmd_S'; }
	}
	/**
	 * 下级联盟摘要信息
	 */
	export class ChildLeagueInfo {
		uid: number;
		headurl: string;
		nickname: string;
		/**
		 * 成员人数
		 */
		memberNum: number;
		/**
		 * 自身基金数量
		 */
		mathPoint: number;
		/**
		 * 成员总基金数量
		 */
		memberMathPoint: number;
		/**
		 * 上级Uid
		 */
		parentUid: number;
		/**
		 * 昨日大赢家数
		 */
		memberbigWinY: number;
		/**
		 * 昨日玩的桌数
		 */
		memberplayNumY: number;
		/**
		 * 昨日税收
		 */
		memberTaxY: number;
		/**
		 * 历史总税收
		 */
		memberTaxAll: number;
		/**
		 * 玩的总桌数
		 */
		memberplayNumA: number;
		/**
		 * 返利比例(本人获得总量的百分比)
		 */
		tax: number;
		GetType(): string { return 'Cmd.ChildLeagueInfo'; }
	}
	/**
	 * 请求下级联盟列表
	 */
	export class RequestChildListLeagueCmd_C {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 某一个合伙人,不指定就是自己
		 */
		uid: number;
		GetType(): string { return 'Cmd.RequestChildListLeagueCmd_C'; }
	}
	/**
	 * 返回下级联盟列表
	 */
	export class ReturnChildListLeagueCmd_S {
		/**
		 * 联盟id
		 */
		leagueId: number;
		uid: number;
		list: ChildLeagueInfo[];
		/**
		 * 所有成员基金总数
		 */
		mathPointAll: number;
		GetType(): string { return 'Cmd.ReturnChildListLeagueCmd_S'; }
	}
	/**
	 * 请求更改下级税收百分比
	 */
	export class ChangeChildTaxLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid
		 */
		childUid: number;
		/**
		 * 返利比例(本人获得总量的百分比)
		 */
		tax: number;
		GetType(): string { return 'Cmd.ChangeChildTaxLeagueCmd_CS'; }
	}
	/**
	 * 请求下级指定联盟的详细信息
	 */
	export class RequestChildMemberInfoLeagueCmd_C {
		/**
		 * 联盟id
		 */
		leagueId: number;
		uid: number;
		GetType(): string { return 'Cmd.RequestChildMemberInfoLeagueCmd_C'; }
	}
	/**
	 * 返回下级指定联盟的详细信息白名单
	 */
	export class ReturnChildMemberInfoLeagueCmd_S {
		/**
		 * 联盟id
		 */
		leagueId: number;
		uid: number;
		whitelist: Cmd.MatchGroupMemberInfo[];
		/**
		 * 当前可提取税收总额
		 */
		taxAll: number;
		/**
		 * 昨日开局总数
		 */
		playNumY: number;
		/**
		 * 成员数量
		 */
		memberNum: number;
		GetType(): string { return 'Cmd.ReturnChildMemberInfoLeagueCmd_S'; }
	}
	/**
	 * 申请加入某个联盟
	 */
	export class JoinLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid,可以不填,超级管理员用
		 */
		childUid: number;
		/**
		 * 上级联盟uid
		 */
		parentId: number;
		/**
		 * 1表示同意
		 */
		agree: number;
		/**
		 * 1表示同时成为合伙人
		 */
		partner: number;
		GetType(): string { return 'Cmd.JoinLeagueCmd_CS'; }
	}
	/**
	 * 回复加入某个联盟
	 */
	export class ReplyJoinLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid,可以不填,超级管理员用
		 */
		childUid: number;
		/**
		 * 1表示同意
		 */
		agree: number;
		GetType(): string { return 'Cmd.ReplyJoinLeagueCmd_CS'; }
	}
	/**
	 * 申请白名单消息列表,玩家请求后主动推给匹配主
	 */
	export class JoinMemberListLeagueCmd_S {
		/**
		 * 匹配号
		 */
		leagueId: number;
		list: Cmd.MatchGroupMemberInfo[];
		GetType(): string { return 'Cmd.JoinMemberListLeagueCmd_S'; }
	}
	/**
	 * 申请退出某个联盟,下级可以主动退出,上级也可以直接踢出
	 */
	export class LeaveLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid,不填表示自己
		 */
		childUid: number;
		GetType(): string { return 'Cmd.LeaveLeagueCmd_CS'; }
	}
	/**
	 * 请求查看某个联盟,如果已经在联盟内,返回ReturnRoomMatchGroupCmd_S
	 */
	export class RequestLeagueCmd_C {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 上级uid
		 */
		parentUid: number;
		GetType(): string { return 'Cmd.RequestLeagueCmd_C'; }
	}
	/**
	 * 邀请某人加入联盟
	 */
	export class InviteLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid
		 */
		childUid: number;
		/**
		 * 上级uid
		 */
		parentId: number;
		/**
		 * 1表示同时成为合伙人
		 */
		partner: number;
		GetType(): string { return 'Cmd.InviteLeagueCmd_CS'; }
	}
	/**
	 * 回复邀请某人加入联盟
	 */
	export class ReplyInviteLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 1表示同意
		 */
		agree: number;
		GetType(): string { return 'Cmd.ReplyInviteLeagueCmd_CS'; }
	}
	/**
	 * 修改某人的联盟关系(调配)
	 */
	export class ChangeLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid
		 */
		childUid: number;
		/**
		 * 上级uid
		 */
		parentId: number;
		/**
		 * 1表示同时成为合伙人
		 */
		partner: number;
		/**
		 * 返利比例(本人获得总量的百分比)
		 */
		tax: number;
		GetType(): string { return 'Cmd.ChangeLeagueCmd_CS'; }
	}
	/**
	 * 修改某人的合伙人关系
	 */
	export class ChangePartnerLeagueCmd_CS {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 下级uid
		 */
		uid: number;
		/**
		 * 0或不填表示撤销合伙人,1表示成为合伙人
		 */
		partner: number;
		/**
		 * 返利比例(本人获得总量的百分比)
		 */
		tax: number;
		GetType(): string { return 'Cmd.ChangePartnerLeagueCmd_CS'; }
	}
	/**
	 * 更换联盟主人,转让
	 */
	export class ChangeOwnerLeagueCmd_C {
		leagueId: number;
		toUid: number;
		GetType(): string { return 'Cmd.ChangeOwnerLeagueCmd_C'; }
	}
	/**
	 * 请求联盟排行榜
	 */
	export class RequestOrderLeagueCmd_C {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 请求排行类型 0或者不填表示 总基金排行 1表示七日大赢家，2表示七日总局数，3表示昨日赢家，4表示昨日输家
		 */
		orderType: number;
		GetType(): string { return 'Cmd.RequestOrderLeagueCmd_C'; }
	}
	/**
	 * 联盟排行榜
	 */
	export class OrderLeague {
		/**
		 * 玩家id
		 */
		uid: number;
		/**
		 * 玩家昵称
		 */
		nickName: string;
		/**
		 * 玩家基金
		 */
		matchPoint: number;
		/**
		 * 大赢家次数
		 */
		bigWinNum: number;
		/**
		 * 总局数
		 */
		playNum: number;
		/**
		 * 赢的次数
		 */
		winNum: number;
		/**
		 * 输的次数
		 */
		loseNum: number;
		GetType(): string { return 'Cmd.OrderLeague'; }
	}
	/**
	 * 请求联盟排行榜
	 */
	export class ReturnOrderLeagueCmd_S {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 请求排行类型 0或者不填表示 总基金排行 1表示七日大赢家，2表示七日总局数，3表示昨日赢家，4表示昨日输家
		 */
		orderType: number;
		/**
		 * 排行榜数据
		 */
		list: OrderLeague[];
		GetType(): string { return 'Cmd.ReturnOrderLeagueCmd_S'; }
	}
	/**
	 * 请求联盟房间贡献明细
	 */
	export class RequestRoomTaxLeagueCmd_C {
		/**
		 * 联盟id
		 */
		leagueId: number;
		GetType(): string { return 'Cmd.RequestRoomTaxLeagueCmd_C'; }
	}
	/**
	 * 联盟房间贡献
	 */
	export class LeagueRoomTax {
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 房间结束时间
		 */
		time: number;
		/**
		 * 贡献基金值
		 */
		tax: number;
		GetType(): string { return 'Cmd.LeagueRoomTax'; }
	}
	/**
	 * 返回联盟房间贡献明细
	 */
	export class ReturnRoomTaxLeagueCmd_S {
		/**
		 * 联盟id
		 */
		leagueId: number;
		/**
		 * 房间贡献列表
		 */
		list: LeagueRoomTax[];
		GetType(): string { return 'Cmd.ReturnRoomTaxLeagueCmd_S'; }
	}
	/**
	 * 请求提取联盟基金
	 */
	export class GetTaxLeagueCmd_C {
		/**
		 * 联盟id
		 */
		leagueId: number;
		GetType(): string { return 'Cmd.GetTaxLeagueCmd_C'; }
	}
	/**
	 * 请求最新操作历史玩家列表
	 */
	export class LatestOperateLeagueCmd_C {
		/**
		 * 操作类型,可以是联盟id,茶楼id或者匹配号id,目前用联盟id
		 */
		opid: number;
		GetType(): string { return 'Cmd.LatestOperateLeagueCmd_C'; }
	}
	export class LatestOperateLeague {
		uid: number;
		/**
		 * optional string    				headurl   	= 3;
		 */
		nickname: string;
		GetType(): string { return 'Cmd.LatestOperateLeague'; }
	}
	/**
	 * 返回最新操作历史玩家列表
	 */
	export class LatestOperateLeagueCmd_S {
		/**
		 * 操作类型,可以是联盟id,茶楼id或者匹配号id,目前用联盟id
		 */
		opid: number;
		list: LatestOperateLeague[];
		GetType(): string { return 'Cmd.LatestOperateLeagueCmd_S'; }
	}
}
