//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 广播系统表.xlsx SHEET: Sheet1
	 */
	export class broadcasttable {
		/**
		 * 编号
		 */
		broadcastid: number;
		/**
		 * 广播类型
		 */
		typeId: number;
		/**
		 * 参数1
		 */
		part1: number[];
		/**
		 * 参数2
		 */
		part2: number;
		/**
		 * 描述
		 */
		describe: string;

		GetType(): string { return 'table.broadcasttable'; }
	}
}
