//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-幸运大转盘.xlsx SHEET: 转盘
	 */
	export class TableTurn {
		/**
		 * 序列
		 */
		id: number;
		/**
		 * 物品
		 */
		name: string;
		/**
		 * ID
		 */
		goodId: number;
		/**
		 * 奖励
		 */
		giftGoods: TableTurn.GiftGoodsItem;
		/**
		 * 概率
		 */
		probability: number;
		/**
		 * 1倍概率
		 */
		probability1: number;
		/**
		 * 2倍概率
		 */
		probability2: number;
		/**
		 * 3倍概率
		 */
		probability3: number;
		/**
		 * 4倍概率
		 */
		probability4: number;

		GetType(): string { return 'table.TableTurn'; }
	}
	export module TableTurn {
		/**
		 * 奖励
		 */
		export class GiftGoodsItem {
			goodId: number;
			goodNbr: number;
		}
	}
}
