//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-创建房间选项.xlsx SHEET: 大厅服务器设置
	 */
	export class TableLobbyServerConfig {
		/**
		 * 大厅ID
		 */
		id: number;
		/**
		 * 红包开奖
		 */
		redEnvelopeReward: number;
		/**
		 * 初始记牌器
		 */
		iniCardplayer: number;
		/**
		 * 手动绑定代理商
		 */
		bindAgent: number;
		/**
		 * 淘汰赛机器人得分
		 */
		robotScore: TableLobbyServerConfig.RobotScoreItem[];
		/**
		 * 俱乐部是否自动刷新
		 */
		clubAutoRefresh: number;
		/**
		 * 群主解散
		 */
		masterDissolve: number;
		/**
		 * 新年活动局数
		 */
		newyearNumber: number[];
		/**
		 * 抽奖耗钻
		 */
		drawCost: number[];
		/**
		 * 开房场抽水
		 */
		pumpPercent2: number;
		/**
		 * 桌面收藏奖励
		 */
		windowsReward: TableLobbyServerConfig.WindowsRewardItem[];
		/**
		 * 开房老司机奖励
		 */
		openReward: TableLobbyServerConfig.OpenRewardItem[];
		/**
		 * 大赢家摘花模式
		 */
		bwfpm: number;
		/**
		 * 摘花方式
		 */
		pickingway: number;

		GetType(): string { return 'table.TableLobbyServerConfig'; }
	}
	export module TableLobbyServerConfig {
		export class RobotScoreItem {
			lowestMark: number;
			highestMark: number;
			probability: number;
		}
	}
	export module TableLobbyServerConfig {
		export class WindowsRewardItem {
			goodId: number;
			goodNumber: number;
		}
	}
	export module TableLobbyServerConfig {
		export class OpenRewardItem {
			rank: number;
			reward: number;
		}
	}
}
