//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 时时彩表.xlsx SHEET: 时时彩概率表
	 */
	export class TableshishicaiChance {
		/**
		 * 序号
		 */
		shishicaiChanceID: number;
		/**
		 * 奖池金币量
		 */
		jackpot: number;
		/**
		 * 开豹子概率
		 */
		leopardChance: number;
		/**
		 * 豹子单双大开概率
		 */
		SingledoubleChance: number;
		/**
		 * 期望第一概率
		 */
		expectedvalue1: number;
		/**
		 * 期望第二概率
		 */
		expectedvalue2: number;
		/**
		 * 期望第三概率
		 */
		expectedvalue3: number;
		/**
		 * 期望第四概率
		 */
		expectedvalue4: number;
		/**
		 * 期望第五概率
		 */
		expectedvalue5: number;
		/**
		 * 期望第六概率
		 */
		expectedvalue6: number;
		/**
		 * 期望第七概率
		 */
		expectedvalue7: number;
		/**
		 * 期望第八概率
		 */
		expectedvalue8: number;
		/**
		 * 期望第九概率
		 */
		expectedvalue9: number;
		/**
		 * 期望第十概率
		 */
		expectedvalue10: number;

		GetType(): string { return 'table.TableshishicaiChance'; }
	}
}
