//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 周边系统.xlsx SHEET: VIP点数 KEY: lobbyId
	 */
	export class TableVIPPoint {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * vip1
		 */
		vip1Point: number;
		/**
		 * vip2
		 */
		vip2Point: number;
		/**
		 * vip3
		 */
		vip3Point: number;
		/**
		 * vip4
		 */
		vip4Point: number;
		/**
		 * vip5
		 */
		vip5Point: number;
		/**
		 * vip6
		 */
		vip6Point: number;
		/**
		 * vip7
		 */
		vip7Point: number;
		/**
		 * vip8
		 */
		vip8Point: number;
		/**
		 * vip9
		 */
		vip9Point: number;
		/**
		 * vip10
		 */
		vip10Point: number;
		/**
		 * vip11
		 */
		vip11Point: number;
		/**
		 * vip12
		 */
		vip12Point: number;
		/**
		 * vip13
		 */
		vip13Point: number;
		/**
		 * 1元vip点
		 */
		pointPerYuan: number;
		/**
		 * 一次奖励
		 */
		vipReward: TableVIPPoint.VipRewardItem[];
		/**
		 * 签到加成
		 */
		signBuff: TableVIPPoint.SignBuffItem[];

		GetType(): string { return 'table.TableVIPPoint'; }
	}
	export module TableVIPPoint {
		export class VipRewardItem {
			vipLevel: number;
			reward: TableVIPPoint.VipRewardItem.RewardItem;
		}
	}
	export module TableVIPPoint {
		export module VipRewardItem {
			export class RewardItem {
				goodsId: number;
				count: number;
			}
		}
	}
	export module TableVIPPoint {
		export class SignBuffItem {
			vipLevel: number;
			percent: number;
		}
	}
}
