//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩排行榜.xlsx SHEET: 排行榜 KEY: lobbyId
	 */
	export class TableRankingList_haocai {
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 财富总榜奖励
		 */
		coinList: TableRankingList_haocai.CoinListItem[];
		/**
		 * 充值榜奖励
		 */
		rechargeList: TableRankingList_haocai.RechargeListItem[];
		/**
		 * 魅力总榜奖励
		 */
		charmtotalList: TableRankingList_haocai.CharmtotalListItem[];
		/**
		 * 魅力周榜奖励
		 */
		charmweekList: TableRankingList_haocai.CharmweekListItem[];
		/**
		 * 游戏盈利榜奖励
		 */
		gameReward: TableRankingList_haocai.GameRewardItem[];
		/**
		 * 金鲨榜
		 */
		jinshabang: TableRankingList_haocai.JinshabangItem[];
		/**
		 * 银鲨榜
		 */
		silversharklist: TableRankingList_haocai.SilversharklistItem[];

		GetType(): string { return 'table.TableRankingList_haocai'; }
	}
	export module TableRankingList_haocai {
		export class CoinListItem {
			rank: number[];
			reward: TableRankingList_haocai.CoinListItem.RewardItem[];
		}
	}
	export module TableRankingList_haocai {
		export module CoinListItem {
			export class RewardItem {
				goodsId: number;
				count: number;
				rType: number;
				desc: string;
			}
		}
	}
	export module TableRankingList_haocai {
		export class RechargeListItem {
			rank: number[];
			reward: TableRankingList_haocai.RechargeListItem.RewardItem[];
		}
	}
	export module TableRankingList_haocai {
		export module RechargeListItem {
			export class RewardItem {
				goodsId: number;
				count: number;
				rType: number;
				desc: string;
			}
		}
	}
	export module TableRankingList_haocai {
		export class CharmtotalListItem {
			rank: number[];
			reward: TableRankingList_haocai.CharmtotalListItem.RewardItem[];
		}
	}
	export module TableRankingList_haocai {
		export module CharmtotalListItem {
			export class RewardItem {
				goodsId: number;
				count: number;
				rType: number;
				desc: string;
			}
		}
	}
	export module TableRankingList_haocai {
		export class CharmweekListItem {
			rank: number[];
			reward: TableRankingList_haocai.CharmweekListItem.RewardItem[];
		}
	}
	export module TableRankingList_haocai {
		export module CharmweekListItem {
			export class RewardItem {
				goodsId: number;
				count: number;
				rType: number;
				desc: string;
			}
		}
	}
	export module TableRankingList_haocai {
		export class GameRewardItem {
			gameId: number;
			lottery: TableRankingList_haocai.GameRewardItem.LotteryItem[];
		}
	}
	export module TableRankingList_haocai {
		export module GameRewardItem {
			export class LotteryItem {
				rank: number[];
				reward: TableRankingList_haocai.GameRewardItem.LotteryItem.RewardItem[];
			}
		}
	}
	export module TableRankingList_haocai {
		export module GameRewardItem {
			export module LotteryItem {
				export class RewardItem {
					goodsId: number;
					count: number;
					rType: number;
				}
			}
		}
	}
	export module TableRankingList_haocai {
		export class JinshabangItem {
			rank: number[];
			reward: TableRankingList_haocai.JinshabangItem.RewardItem[];
		}
	}
	export module TableRankingList_haocai {
		export module JinshabangItem {
			export class RewardItem {
				goodsId: number;
				count: number;
				rType: number;
				desc: string;
			}
		}
	}
	export module TableRankingList_haocai {
		export class SilversharklistItem {
			rank: number[];
			reward: TableRankingList_haocai.SilversharklistItem.RewardItem[];
		}
	}
	export module TableRankingList_haocai {
		export module SilversharklistItem {
			export class RewardItem {
				goodsId: number;
				count: number;
				rType: number;
				desc: string;
			}
		}
	}
}
