//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-创建房间选项.xlsx SHEET: 单个麻将设置 KEY: gameId
	 */
	export class TableCreateConfigList {
		/**
		 * 序列
		 */
		id: number;
		/**
		 * 游戏ID
		 */
		gameId: number;
		/**
		 * 类型
		 */
		type: number;
		/**
		 * 游戏首字母
		 */
		gameFirstCharge: string;
		/**
		 * 录像不开启
		 */
		videoOpen: number;
		/**
		 * 无时间选项
		 */
		timeLimit: number;
		/**
		 * 游戏名称
		 */
		gameName: string;
		/**
		 * 人数
		 */
		baseUserNbr: number[];
		/**
		 * 人数选择
		 */
		userNbr: TableCreateConfigList.UserNbrItem[];
		/**
		 * 玩法选择
		 */
		playType: TableCreateConfigList.PlayTypeItem[];
		/**
		 * 默认玩法选择
		 */
		defaltPlayType: number[];
		/**
		 * 底注设置
		 */
		basebetConfig: number[];
		/**
		 * 局数选择
		 */
		gameNbr: TableCreateConfigList.GameNbrItem[];
		/**
		 * 收费模式
		 */
		payType: TableCreateConfigList.PayTypeItem[];
		/**
		 * 房主小费
		 */
		hostTip: TableCreateConfigList.HostTipItem[];
		/**
		 * 可中途加入
		 */
		halfJoin: number;
		/**
		 * 底分
		 */
		basePoint: TableCreateConfigList.BasePointItem[];
		/**
		 * 时间选择
		 */
		outTime: TableCreateConfigList.OutTimeItem[];
		/**
		 * 是否开启
		 */
		open: number;
		/**
		 * 游戏分享标题
		 */
		gameshareTitle: string;
		/**
		 * 游戏分享内容
		 */
		gameshareContent: string;
		/**
		 * 固定房卡分享
		 */
		fixroomShare: number;
		/**
		 * 游戏分享内容不要房号
		 */
		gameshareContentnoroomnum: number;
		/**
		 * 创建面板版号展示
		 */
		banhaoTab: string;
		/**
		 * 是否减半
		 */
		isithalved: number;
		/**
		 * 代金券
		 */
		cashCoupon: number[];

		GetType(): string { return 'table.TableCreateConfigList'; }
	}
	export module TableCreateConfigList {
		export class UserNbrItem {
			value: number;
			label: string;
		}
	}
	export module TableCreateConfigList {
		export class PlayTypeItem {
			label: string;
			idArr: number[];
		}
	}
	export module TableCreateConfigList {
		export class GameNbrItem {
			value: number;
			label: string;
		}
	}
	export module TableCreateConfigList {
		export class PayTypeItem {
			value: number;
			label: string;
		}
	}
	export module TableCreateConfigList {
		export class HostTipItem {
			value: number;
			label: string;
			tipValue: number;
		}
	}
	export module TableCreateConfigList {
		export class BasePointItem {
			value: number;
			label: string;
		}
	}
	export module TableCreateConfigList {
		export class OutTimeItem {
			value: number;
			label: string;
		}
	}
}
