//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 摇一摇.xlsx SHEET: 摇一摇
	 */
	export class TableShake {
		/**
		 * 序列
		 */
		id: number;
		/**
		 * 原价
		 */
		originalPrice: string;
		/**
		 * 现价
		 */
		presentPprice: string;
		/**
		 * 商品
		 */
		commodity: number;
		/**
		 * 概率
		 */
		probability: number;
		/**
		 * 赠送金币
		 */
		give: number;
		/**
		 * 免费摇
		 */
		freeShake: number[];
		/**
		 * 金币摇
		 */
		goldShake: number[];
		/**
		 * 免费次数
		 */
		freeTimes: number;
		/**
		 * 每日购买次数
		 */
		purchase: number;
		/**
		 * 单次消耗金币
		 */
		consume: number;
		/**
		 * 开始时间
		 */
		startTime: string;
		/**
		 * 结束时间
		 */
		endTime: string;
		/**
		 * 活动时间
		 */
		actTime: number;

		GetType(): string { return 'table.TableShake'; }
	}
}
