//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 特殊账号.xlsx SHEET: 审核白名单
	 */
	export class TableCheckID {
		id: number;

		GetType(): string { return 'table.TableCheckID'; }
	}
}
