//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-房费.xlsx SHEET: 房费
	 */
	export class TableRoomCostConfig {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 人数
		 */
		usernbr: number;
		/**
		 * 局数
		 */
		gamenbr: number;
		/**
		 * 开房费用
		 */
		diamondcost: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 游戏ID
		 */
		gameId: number[];
		/**
		 * 均摊费用
		 */
		averdiamondcost: number;
		/**
		 * 新大赢家费用
		 */
		newbigwinnercost: number;

		GetType(): string { return 'table.TableRoomCostConfig'; }
	}
}
