//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 商城vip.xlsx SHEET: 商城VIP
	 */
	export class TableVIP {
		/**
		 * 序列
		 */
		roomType: number;
		/**
		 * vip等级
		 */
		VIPRank: number;
		/**
		 * 充值金额
		 */
		ADDRMB: number[];
		/**
		 * 特权描述
		 */
		VIPDescribe: string;

		GetType(): string { return 'table.TableVIP'; }
	}
}
