//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby_room.proto
/// <reference path="common.ts" />

module Cmd {
	export class WinnerFlowerLadder {
		/**
		 * 输赢分数值
		 */
		winnerLimitScore: number;
		/**
		 * 摘花数
		 */
		winnerFlower: number;
		GetType(): string { return 'Cmd.WinnerFlowerLadder'; }
	}
	/**
	 * 请求当前正常运营的游戏列表
	 */
	export class GetNormalGameListRoomCmd_C {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * 1/2/3 普通场、练习场、匹配场  默认为1 兼容以前模式
		 */
		typ: number;
		/**
		 * 是否俱乐部请求 1:是 0:不是
		 */
		isClub: number;
		/**
		 * 客户端上传游戏版本列表的md5 用于子游戏的版本更新
		 */
		md5GameList: string;
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.GetNormalGameListRoomCmd_C'; }
	}
	export class GetNormalGameListRoomCmd_S {
		/**
		 * 返回码 存在返回码则是有误
		 */
		resultCode: number;
		/**
		 * 1/2/3 普通场、练习场、匹配场  默认为1 兼容以前模式
		 */
		typ: number;
		/**
		 * 正常前端可选择的游戏列表id
		 */
		gameIdList: number[];
		/**
		 * 上次创建数据
		 */
		lastCreate: CreateRoomCmd_C;
		/**
		 * 免费开始时间 如果该字段不为Nil则代表当前处于免费时间内
		 */
		startTime: number;
		/**
		 * 免费结束时间
		 */
		endTime: number;
		/**
		 * 是否俱乐部请求 1:是 0:不是
		 */
		isClub: number;
		/**
		 * TableLobbyGameList配置数据
		 */
		tableLobbyGame: string;
		/**
		 * 游戏版本json数据 用于子游戏的版本更新
		 */
		gameVersionList: string;
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.GetNormalGameListRoomCmd_S'; }
	}
	/**
	 * 获取当前练习场
	 */
	export class GetPracticeGameInfoRoomCmd_C {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * 暂时由服务器默认分配第一个的话 这里不传
		 */
		gameId: number;
		/**
		 * 初中高 1/2/3
		 */
		level: number;
		GetType(): string { return 'Cmd.GetPracticeGameInfoRoomCmd_C'; }
	}
	export class GetPracticeGameInfoRoomCmd_S {
		/**
		 * 返回码 存在返回码则是有误
		 */
		resultCode: number;
		/**
		 * 游戏id
		 */
		gameId: number;
		/**
		 * 区id
		 */
		zoneId: number;
		GetType(): string { return 'Cmd.GetPracticeGameInfoRoomCmd_S'; }
	}
	/**
	 * 创建房间
	 */
	export class CreateRoomCmd_C {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 当前房间创建局数
		 */
		gameNbr: number;
		/**
		 * 玩法
		 */
		playType: number;
		/**
		 * 房间模式  二人、四人
		 */
		userNbr: number;
		/**
		 * 房间支付类型
		 */
		payType: number;
		/**
		 * 峰值
		 */
		multiplePeak: number;
		/**
		 * 出牌时间
		 */
		outTime: number;
		/**
		 * 房主小费
		 */
		hostTip: number;
		/**
		 * 大厅不校验的数据,给游戏校验
		 */
		props: number[];
		/**
		 * 当前正常开始 是否存在对赌
		 */
		gamble: number;
		/**
		 * 对赌类型 1/2 金币/钻石 默认不传为赌金币
		 */
		gambleType: number;
		/**
		 * 输赢上限  (好彩真人金币场)
		 */
		winLimit: number;
		/**
		 * 加倍起番  (好彩真人金币场)
		 */
		ratio: number;
		/**
		 * 底分
		 */
		basePoint: number;
		/**
		 * 底注
		 */
		bottomPoint: number;
		/**
		 * 入场
		 */
		enteringPoint: number;
		/**
		 * 离场
		 */
		leavingPoint: number;
		/**
		 * 返回当前游戏的名称 好牌网俱乐部需要
		 */
		gameName: string;
		/**
		 * 0:不允许 1:允许 是否允许陌生人加入(芝麻斗牌 好友房)
		 */
		bAllowStranger: number;
		/**
		 * 是否需要听牌提示 nil/1:开/关
		 */
		listenTips: number;
		/**
		 *  这堆参数当前只用于回复给前端创建面板的数据
		 *  1分几朵花 -- 若存在该参数表示为红花房
		 */
		baseFlower: number;
		/**
		 * 进房最低下限
		 */
		lowerLimitFlower: number;
		/**
		 * 大赢家摘花时 玩家输赢分数下限 -- 若存在该参数表示为大赢家摘花
		 */
		winnerLimitScore: number;
		/**
		 * 大赢家摘花数 -- 若存在该参数表示为大赢家摘花
		 */
		winnerFlower: number;
		/**
		 * AA摘花数 -- 若存在该参数表示为AA摘花
		 */
		AAFlower: number;
		/**
		 * 大赢家摘花类型 多种模式共存的大厅 通过前端指定摘花模式 nil/1/2 大于多少分摘多少花、每多少分摘多少花、阶梯摘花
		 */
		winnerFlowerType: number;
		/**
		 * 选阶梯摘花时的具体数值
		 */
		winnerFlowerLadder: WinnerFlowerLadder[];
		GetType(): string { return 'Cmd.CreateRoomCmd_C'; }
	}
	export class CreateRoomCmd_S {
		/**
		 * 返回码 存在返回码则是有误
		 */
		resultCode: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 区id
		 */
		zoneId: number;
		/**
		 * 全局唯一的房间id
		 */
		globalRoomId: number;
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 分享数据
		 */
		shareInfo: Cmd.ShareInfo;
		/**
		 * gameGatewayUrl,尽量让玩家跟房主一个url,防止被攻击
		 */
		url: string;
		/**
		 * 如果不为空表示为匹配场
		 */
		scene: number;
		/**
		 * 不进入游戏
		 */
		notIntoGame: number;
		/**
		 * 该房间创建时为几人房 -- 牛牛人数不同ui不一致
		 */
		baseUserNbr: number;
		/**
		 * 游戏版本json数据 用于子游戏的版本更新
		 */
		gameVersionList: string;
		matchId: number;
		GetType(): string { return 'Cmd.CreateRoomCmd_S'; }
	}
	/**
	 * 请求踢人
	 */
	export class KickLeaveRoomCmd_C {
		uid: number;
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 匹配号的传下匹配号id
		 */
		matchId: number;
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.KickLeaveRoomCmd_C'; }
	}
	/**
	 * 请求解散房间
	 */
	export class ActiveDissolveRoomCmd_C {
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 匹配号的传下匹配号id
		 */
		matchId: number;
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.ActiveDissolveRoomCmd_C'; }
	}
	/**
	 * 查看正在进行中的房间(多开房间用)
	 */
	export class ActiveCreateRoomCmd_C {
		GetType(): string { return 'Cmd.ActiveCreateRoomCmd_C'; }
	}
	export class ActiveCreateRoomCmd_S {
		/**
		 * 本匹配号所产生的所有房间号
		 */
		roomList: Cmd.MathGroupRoomInfo[];
		GetType(): string { return 'Cmd.ActiveCreateRoomCmd_S'; }
	}
	export class ActiveDetailRoomCmd_C {
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * globalRoomId
		 */
		gid: number;
		/**
		 * 匹配号的传下匹配号id
		 */
		matchId: number;
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.ActiveDetailRoomCmd_C'; }
	}
	export class ActiveDetailRoomCmd_S {
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * globalRoomId
		 */
		gid: number;
		/**
		 * 不填或0表示准备中,1表示已开局
		 */
		state: number;
		/**
		 * 成员信息
		 */
		list: Cmd.MatchGroupMemberInfo[];
		/**
		 * 匹配号的回下匹配号id
		 */
		matchId: number;
		/**
		 * 摘花玩法描述
		 */
		flowerTypeDesc: string;
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.ActiveDetailRoomCmd_S'; }
	}
	/**
	 * 返回房间
	 */
	export class ReturnRoomCmd_C {
		/**
		 * 返回房间需要带上lobbyId
		 */
		lobbyId: number;
		GetType(): string { return 'Cmd.ReturnRoomCmd_C'; }
	}
	export class ReturnRoomCmd_S {
		/**
		 * 返回码 存在返回码则是有误
		 */
		resultCode: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 区id
		 */
		zoneId: number;
		/**
		 * 全局唯一的房间id
		 */
		globalRoomId: number;
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 分享数据
		 */
		shareInfo: Cmd.ShareInfo;
		/**
		 * gameGatewayUrl,尽量让玩家跟房主一个url,防止被攻击
		 */
		url: string;
		/**
		 * 房间类型RoomType
		 */
		roomType: number;
		/**
		 * 如果不为空表示为匹配场
		 */
		scene: number;
		/**
		 * 该房间创建时为几人房 -- 牛牛人数不同ui不一致
		 */
		baseUserNbr: number;
		matchId: number;
		GetType(): string { return 'Cmd.ReturnRoomCmd_S'; }
	}
	/**
	 * 加入房间
	 */
	export class EnterRoomCmd_C {
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 進入房间需要带上lobbyId（指定房間id可能不是該大廳的）
		 */
		lobbyId: number;
		/**
		 * 匹配号桌子相关: nil、-1、0、0以上 匹配号内快速匹配、直接进到俱乐部界面、匹配号创建新房间、匹配号内主动加入某房间
		 */
		preBestRoomId: number;
		/**
		 * 俱乐部授权房间认证多一个备注流程。正常进入流程不传、申请授权界面传入备注 玩家不填也必须传空字符串 不能不传。
		 */
		note: string;
		/**
		 * 当前楼层id
		 */
		floorId: number;
		/**
		 * 指定玩法层 可多选
		 */
		playFloorIdLists: number[];
		/**
		 * 是否为SZ大联盟模式 1：表示为SZ大联盟模式
		 */
		isSZLeague: number;
		GetType(): string { return 'Cmd.EnterRoomCmd_C'; }
	}
	export class EnterRoomCmd_S {
		/**
		 * 返回码 存在返回码则是有误
		 */
		resultCode: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 区id
		 */
		zoneId: number;
		/**
		 * 全局唯一的房间id
		 */
		globalRoomId: number;
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 分享数据
		 */
		shareInfo: Cmd.ShareInfo;
		/**
		 * gameGatewayUrl,尽量让玩家跟房主一个url,防止被攻击
		 */
		url: string;
		/**
		 * 如果不为空表示为匹配场
		 */
		scene: number;
		roomState: Cmd.RoomState;
		/**
		 * 该房间创建时为几人房 -- 牛牛人数不同ui不一致
		 */
		baseUserNbr: number;
		/**
		 * 游戏版本json数据 用于子游戏的版本更新
		 */
		gameVersionList: string;
		matchId: number;
		GetType(): string { return 'Cmd.EnterRoomCmd_S'; }
	}
	/**
	 * 进入俱乐部 需要弹出申请备注流程
	 */
	export class NotifyImportNoteCmd_S {
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 進入房间需要带上lobbyId（指定房間id可能不是該大廳的）
		 */
		lobbyId: number;
		/**
		 * 俱乐部内进入的指定桌子从这里传 nil/0/0以上  不传为以前的默认、主动创建新的、加入指定的
		 */
		preBestRoomId: number;
		GetType(): string { return 'Cmd.NotifyImportNoteCmd_S'; }
	}
	/**
	 * 房间解散时 由大厅统一推条消息通知房间创建者
	 */
	export class RemoveRoomCmd_Brd {
		/**
		 * 房间解散 给房主推送该通知时 带上其当前房卡数量
		 */
		card: number;
		GetType(): string { return 'Cmd.RemoveRoomCmd_Brd'; }
	}
	/**
	 * 创建的房间已被其他四个玩家玩了 则推送一条消息给玩家 通知其 当前可创建房间了
	 */
	export class CanCreateRoomCmd_Brd {
		/**
		 * 房间号
		 */
		roomId: number;
		/**
		 * 当前钻石
		 */
		diamond: number;
		GetType(): string { return 'Cmd.CanCreateRoomCmd_Brd'; }
	}
	export class SysMessageMahjongLobbyCmd_S {
		desc: string;
		/**
		 * 消息级别和位置相关  null/1  中度提示条、弹框确定
		 */
		pos: number;
		/**
		 * 要打开的窗口id
		 */
		openWindow: number;
		/**
		 * 返回码 客户端根据去选择语言版本（2018.05.08好彩金币系列）
		 */
		errorCode: number;
		GetType(): string { return 'Cmd.SysMessageMahjongLobbyCmd_S'; }
	}
	/**
	 * 请求续局
	 */
	export class ApplyContinuePlayRoomCmd_C {
		GetType(): string { return 'Cmd.ApplyContinuePlayRoomCmd_C'; }
	}
	export class ApplyContinuePlayRoomCmd_S {
		/**
		 * 返回码
		 */
		resultCode: number;
		GetType(): string { return 'Cmd.ApplyContinuePlayRoomCmd_S'; }
	}
	/**
	 * 续局请求广播
	 */
	export class ApplyContinuePlayRoomCmd_Brd {
		/**
		 * 续局的具体数据 可要可不要
		 */
		desc: string;
		/**
		 * 房间id
		 */
		roomId: number;
		/**
		 * 续局发起者
		 */
		owner: string;
		/**
		 * 玩法层id
		 */
		playfloorid: number;
		/**
		 * 楼层id
		 */
		floorid: number;
		GetType(): string { return 'Cmd.ApplyContinuePlayRoomCmd_Brd'; }
	}
	/**
	 * 请求播放录像
	 */
	export class RequestRecordLobbyCmd_C {
		/**
		 * 全局唯一的房间id
		 */
		globalRoomId: number;
		/**
		 * 如果没有穿globalid,就用roomid反射成globalid,有可能重复,但是先忽略
		 */
		roomId: number;
		/**
		 * 第几局
		 */
		curGameNbr: number;
		/**
		 * globalRoomId:curGameNbr,兼容方式跑起来
		 */
		recordStr: string;
		GetType(): string { return 'Cmd.RequestRecordLobbyCmd_C'; }
	}
	/**
	 * 返回播放录像
	 */
	export class ReturnRecordLobbyCmd_S {
		/**
		 * 录像数据
		 */
		data: string;
		/**
		 * 需要返回gameid,客户端要找
		 */
		gameId: number;
		/**
		 * 主视角uid
		 */
		uid: number;
		/**
		 * 返回码 成功不返回,错误返回非0
		 */
		resultCode: number;
		/**
		 * 第几局
		 */
		curGameNbr: number;
		/**
		 * 总共几局
		 */
		gameNbr: number;
		/**
		 * 几人
		 */
		userNbr: number;
		/**
		 * 房号
		 */
		roomId: number;
		/**
		 * 房间开始时间
		 */
		startTime: number;
		GetType(): string { return 'Cmd.ReturnRecordLobbyCmd_S'; }
	}
	/**
	 * 请求暂停录像
	 */
	export class RequestPauseRecordRoomCmd_C {
		/**
		 * 1表示暂停,2表示继续
		 */
		pause: number;
		GetType(): string { return 'Cmd.RequestPauseRecordRoomCmd_C'; }
	}
	/**
	 * 请求进退录像
	 */
	export class RequestStepRecordRoomCmd_C {
		/**
		 * 负数表示后退,正数表示钱进
		 */
		step: number;
		GetType(): string { return 'Cmd.RequestStepRecordRoomCmd_C'; }
	}
	/**
	 * 请求退出录像
	 */
	export class RequestStopRecordRoomCmd_C {
		GetType(): string { return 'Cmd.RequestStopRecordRoomCmd_C'; }
	}
	/**
	 * 给大厅客户端推送指定房间当前分享数据
	 */
	export class PushRoomShareInfoRoomCmd_S {
		/**
		 * 房间标识（暂时为房间id的string模式、后期可能为随机映射字符串）
		 */
		roomFlag: string;
		/**
		 * 当前已进玩家人数
		 */
		curUserNbr: number;
		/**
		 * 游戏人数（创建房间的人数）
		 */
		userNbr: number;
		GetType(): string { return 'Cmd.PushRoomShareInfoRoomCmd_S'; }
	}
	/**
	 *  匹配场(金币场)--------------------------------------------------------------------------------------------
	 *  进入某一匹配场
	 */
	export class EnterMatchRoomCmd_C {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 场次id
		 */
		scene: number;
		/**
		 * 匹配场 对赌类型 1/2 金币／钻石(暂时可不传 预留)
		 */
		gambleType: number;
		GetType(): string { return 'Cmd.EnterMatchRoomCmd_C'; }
	}
	export class EnterMatchRoomCmd_S {
		resultCode: number;
		GetType(): string { return 'Cmd.EnterMatchRoomCmd_S'; }
	}
	/**
	 * 客家棋牌活动 推荐排行榜--------------------------------------------------------------------------------------------
	 */
	export class InviteRankInfo {
		uid: number;
		nickName: string;
		num: number;
		/**
		 * 头像url
		 */
		headUrl: string;
		GetType(): string { return 'Cmd.InviteRankInfo'; }
	}
	export class IntoInviteRankLobbyCmd_C {
		GetType(): string { return 'Cmd.IntoInviteRankLobbyCmd_C'; }
	}
	export class IntoInviteRankLobbyCmd_S {
		/**
		 * 返回码 存在返回码则是有误
		 */
		resultCode: number;
		infos: InviteRankInfo[];
		myNum: number;
		GetType(): string { return 'Cmd.IntoInviteRankLobbyCmd_S'; }
	}
	/**
	 * 好彩真人麻将，进入房间之前的判断
	 */
	export class GamePara {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 场次id
		 */
		scene: number;
		/**
		 * 匹配场 对赌类型 1/2 金币／钻石(暂时可不传 预留)
		 */
		gambleType: number;
		/**
		 * 测试服允许前端指定区服id
		 */
		preZoneId: number;
		GetType(): string { return 'Cmd.GamePara'; }
	}
	export class JudgeEnterGameLobbyCmd_C {
		/**
		 * 1匹配场  2百人场 3百人场体验场
		 */
		enter: number;
		/**
		 * 房间相关参数
		 */
		gamePara: GamePara;
		GetType(): string { return 'Cmd.JudgeEnterGameLobbyCmd_C'; }
	}
	export class JudgeEnterGameLobbyCmd_S {
		resultCode: number;
		/**
		 * 之前所在房间的游戏类型 1匹配场  2百人场
		 */
		enter: number;
		/**
		 * 房间相关参数
		 */
		gamePara: GamePara;
		GetType(): string { return 'Cmd.JudgeEnterGameLobbyCmd_S'; }
	}
	/**
	 * 好彩真人麻将，返回之前的游戏
	 */
	export class ReturnHaoCaiGameLobbyCmd_C {
		lobbyId: number;
		GetType(): string { return 'Cmd.ReturnHaoCaiGameLobbyCmd_C'; }
	}
	export class ReturnHaoCaiGameLobbyCmd_S {
		resultCode: number;
		GetType(): string { return 'Cmd.ReturnHaoCaiGameLobbyCmd_S'; }
	}
	/**
	 * -----------------------------对赌场相关--------------------
	 *  请求对赌房间信息
	 */
	export class RequestGambleRoomInfoLobbyCmd_C {
		lobbyId: number;
		gameId: number;
		/**
		 * 是否刷新 nil:不是 1:是
		 */
		bRefresh: number;
		GetType(): string { return 'Cmd.RequestGambleRoomInfoLobbyCmd_C'; }
	}
	export class RequestGambleRoomInfoLobbyCmd_S {
		gambleRoomInfos: GambleRoomInfo[];
		/**
		 * 上次进入房间场次  1:匹配房 2:好友房
		 */
		roomType: number;
		/**
		 * 上次进入游戏ID
		 */
		gameId: number;
		GetType(): string { return 'Cmd.RequestGambleRoomInfoLobbyCmd_S'; }
	}
	export class GambleRoomInfo {
		gameId: number;
		/**
		 * 1:匹配房 2:好友房
		 */
		roomType: number;
		/**
		 * 1:金币 2:钻石
		 */
		gambleType: number;
		/**
		 * 底注
		 */
		basePoint: number;
		/**
		 * 进场
		 */
		enteringPoint: number;
		/**
		 * 离场
		 */
		leavingPoint: number;
		/**
		 * 当前人数
		 */
		curUserNbr: number;
		/**
		 * 好友房 几人场
		 */
		userNbr: number;
		/**
		 * 匹配房 场次
		 */
		scene: number;
		/**
		 * 匹配房 1:繁忙 0:流畅
		 */
		isBusy: number;
		/**
		 * 好友房 玩法
		 */
		props: number[];
		/**
		 * 好友房 房间roomid
		 */
		roomId: number;
		GetType(): string { return 'Cmd.GambleRoomInfo'; }
	}
	/**
	 * 请求最终进入的房间的一些信息
	 */
	export class GetGambleRoomInfoLobbyCmd_C {
		lobbyId: number;
		GetType(): string { return 'Cmd.GetGambleRoomInfoLobbyCmd_C'; }
	}
	export class GetGambleRoomInfoLobbyCmd_S {
		/**
		 * 1:金币 2:钻石
		 */
		gambleType: number;
		GetType(): string { return 'Cmd.GetGambleRoomInfoLobbyCmd_S'; }
	}
}
