//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: mahjong_common.proto
/// <reference path="common.ts" />

module uniLib {
	/**
	 * ---------------------------------公共模块----------------------------//
	 */
	export enum CommonModel {
		/**
		 * 充值
		 */
		RECHARGE = 1,
		/**
		 * 在线礼包
		 */
		ONLINE_GIFT = 2,
		/**
		 * 背包
		 */
		BAG = 3,
		/**
		 * 活动中心
		 */
		ACTIVITY = 4,
		/**
		 * 个人信息
		 */
		MY = 5,
		/**
		 * 大厅底部菜单
		 */
		LOBBY_MAIN_MENU = 6,
		/**
		 * 游戏头部聊天
		 */
		TOP_CHAT = 7,
		/**
		 * 查看玩家信息
		 */
		USERINFO = 8,
		/**
		 * 兑换话费卡
		 */
		EXCHANGE_PHONECARD = 9,
		/**
		 * 大厅公告
		 */
		LOBBY_NOTICE = 10,
		/**
		 * 设置
		 */
		LOBBY_SETTING = 11
	}
	/**
	 * ---------------------------------公共消息----------------------------//
	 * 游戏发送给大厅
	 */
	export enum CommonEvent_G2L {
		/**
		 * 领取在线礼包
		 */
		GET_ONLIEN_GIFT = 1
	}
	/**
	 * 大厅发送给游戏
	 */
	export enum CommonEvent_L2G {
		/**
		 * 在线礼包时间更新
		 */
		GET_ONLIEN_GIFT_TIME = 1,
		/**
		 * 在线礼包时间完成
		 */
		ON_ONLIEN_GIFT_TIME_END = 2,
		/**
		 * 设置面板
		 */
		ON_SETTING = 3,
		/**
		 * 设置面板
		 */
		ON_HELP = 4
	}
	/**
	 * 任务事件
	 */
	export enum TaskEventEnum {
		/**
		 * 分享
		 */
		SHARE = 1,
		/**
		 * 上庄
		 */
		BANKER = 2,
		/**
		 * 玩游戏
		 */
		GAME = 3,
		/**
		 * 充值
		 */
		RECHAR = 4,
		/**
		 * 金币数量
		 */
		CHIPS = 5,
		/**
		 * 登陆
		 */
		LOGIN = 6
	}
	export class Any {
		GetType(): string { return 'uniLib.Any'; }
	}
}
