//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 头像框动画表.xlsx SHEET: Sheet1
	 */
	export class headMc {
		id: number;
		/**
		 * 头像动画
		 */
		head_mc: string[];

		GetType(): string { return 'table.headMc'; }
	}
}
