//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: Vip资源表.xlsx SHEET: Sheet1
	 */
	export class TableVip {
		id: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * VIP等级
		 */
		level: number;
		/**
		 * 头像框
		 */
		head_frame: string;
		/**
		 * 大ICON
		 */
		icon_big: string;
		/**
		 * 小ICON
		 */
		icon_small: string;
		/**
		 * 昵称颜色
		 */
		nickNameColor: string;
		/**
		 * 头像动画ID
		 */
		head_mc: number;

		GetType(): string { return 'table.TableVip'; }
	}
}
