//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-新年活动开奖份额.xlsx SHEET: 红包
	 */
	export class NewYearEnvelopeNumberConfig {
		id: number;
		/**
		 * 金额
		 */
		noCard: number[];
		/**
		 * 数量
		 */
		number: number;
		/**
		 * 类型
		 */
		rewardType: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;

		GetType(): string { return 'table.NewYearEnvelopeNumberConfig'; }
	}
}
