//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-新年活动开奖份额.xlsx SHEET: 新年活动消耗
	 */
	export class NewYearRewardNumber {
		/**
		 * 大厅ID
		 */
		id: number;
		/**
		 * 活动开关
		 */
		newyearSwitch: number;
		/**
		 * 公众号名称
		 */
		wechatName: string;
		/**
		 * 新年活动局数
		 */
		newyearNumber: number[];
		/**
		 * 最低提取
		 */
		smallestNumber: number[];
		/**
		 * 最低记录
		 */
		smallestRecord: number[];
		/**
		 * 抽奖耗钻
		 */
		drawCost: number[];

		GetType(): string { return 'table.NewYearRewardNumber'; }
	}
}
