//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 首充配置表.xlsx SHEET: 快速充值
	 */
	export class QuickShop {
		id: number;
		/**
		 * 商城ID
		 */
		shopID: number;

		GetType(): string { return 'table.QuickShop'; }
	}
}
