//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-红包开奖份额表.xlsx SHEET: 红包
	 */
	export class RedEnvelopeNumberConfig {
		id: number;
		/**
		 * 金额
		 */
		cost: number;
		/**
		 * 数量
		 */
		number: number;
		/**
		 * 合计
		 */
		total: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;

		GetType(): string { return 'table.RedEnvelopeNumberConfig'; }
	}
}
