//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 幸运翻翻翻V3.xlsx SHEET: 幸运翻翻翻
	 */
	export class TableLuckySpadeV3 {
		/**
		 * 轮数
		 */
		luckRound: number;
		/**
		 * 对局数
		 */
		totalRound: number;
		/**
		 * 免费奖励
		 */
		freeTurn: number;
		/**
		 * 暴击消耗金币
		 */
		costChips: number;
		/**
		 * 暴击奖励
		 */
		chipsTurn: number[];

		GetType(): string { return 'table.TableLuckySpadeV3'; }
	}
}
