//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 周边系统.xlsx SHEET: 好彩转盘 KEY: lobbyId
	 */
	export class TableluckyTurntable {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 签到奖励
		 */
		signReward: TableluckyTurntable.SignRewardItem[];
		/**
		 * 连续签到
		 */
		continueSign: TableluckyTurntable.ContinueSignItem[];
		/**
		 * vip奖励翻倍
		 */
		vipAdd: number;

		GetType(): string { return 'table.TableluckyTurntable'; }
	}
	export module TableluckyTurntable {
		export class SignRewardItem {
			goodsId: number;
			count: number;
			chance: number;
		}
	}
	export module TableluckyTurntable {
		export class ContinueSignItem {
			dayNum: number;
			reward: TableluckyTurntable.ContinueSignItem.RewardItem;
		}
	}
	export module TableluckyTurntable {
		export module ContinueSignItem {
			export class RewardItem {
				goodsId: number;
				count: number;
			}
		}
	}
}
