//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 幸运翻翻翻.xlsx SHEET: 幸运翻翻翻
	 */
	export class TableLuckySpade {
		/**
		 * 轮数
		 */
		Number: number;
		/**
		 * 对局数
		 */
		localNumbers: number;
		/**
		 * 免费奖励
		 */
		freeReward: number[];
		/**
		 * 钻石消耗
		 */
		diamondConsumption: number;
		/**
		 * 钻石奖励
		 */
		diamondAward: number[];
		/**
		 * 开始时间
		 */
		startTime: string;
		/**
		 * 结束时间
		 */
		endTime: string;

		GetType(): string { return 'table.TableLuckySpade'; }
	}
}
