//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 会员.xlsx SHEET: 会员 KEY: vipLevel
	 */
	export class TableMahjongVipConfig {
		/**
		 * VIP等级
		 */
		vipLevel: number;
		/**
		 * 所需累冲钻石
		 */
		diamond: number;
		/**
		 * 免费场次
		 */
		freeType: number[];
		/**
		 * 充值优惠
		 */
		discount: number;
		/**
		 * 功能描述
		 */
		desc: string[];

		GetType(): string { return 'table.TableMahjongVipConfig'; }
	}
}
