//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩礼物表.xlsx SHEET: 礼物 KEY: giftId
	 */
	export class TableGift_haocai {
		/**
		 * id
		 */
		giftId: number;
		/**
		 * name
		 */
		giftName: string;
		/**
		 * chips
		 */
		giftCost: number;
		/**
		 * charm
		 */
		giftCharm: number;
		classifier: string;

		GetType(): string { return 'table.TableGift_haocai'; }
	}
}
