//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 头衔等级表.xlsx SHEET: Sheet1
	 */
	export class Tablehonour {
		/**
		 * 序列
		 */
		honourID: number;
		/**
		 * 持有金币量
		 */
		holdCoin: number;
		/**
		 * 称号
		 */
		honourTitle: string;

		GetType(): string { return 'table.Tablehonour'; }
	}
}
