//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 消息红点配置.xlsx SHEET: Sheet1 KEY: lobbyId
	 */
	export class TableRedPointConfig {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * 礼品屋
		 */
		GiftHouse: number;
		/**
		 * vip
		 */
		Task_VIP: number;
		/**
		 * 商城
		 */
		Shop_New: number;
		/**
		 * 好友消息
		 */
		FriendMsg: number;
		/**
		 * 好友请求
		 */
		FriendReq: number;
		/**
		 * 好友
		 */
		Friend: number;
		/**
		 * 救济金
		 */
		GetAlms: number;
		/**
		 * 每日签到
		 */
		Act_DaySign: number;
		/**
		 * 幸运翻翻翻
		 */
		Act_TurnCard: number;
		/**
		 * 免费翻牌
		 */
		freeFlop: number;
		/**
		 * 金币翻牌
		 */
		goldcoinFlop: number;
		/**
		 * 幸运大转盘
		 */
		Act_TurnTable: number;
		/**
		 * 摇一摇
		 */
		Act_shake: number;
		/**
		 * 活动
		 */
		Act: number;
		/**
		 * 挑战任务
		 */
		Task_fight: number;
		/**
		 * 充值任务
		 */
		Task_TurnTable: number;
		/**
		 * 福利或任务
		 */
		Task: number;
		/**
		 * 公告
		 */
		Task_Notice: number;
		/**
		 * 魅力值
		 */
		Task_Charm: number;
		/**
		 * 邮件
		 */
		Task_NewMail: number;
		/**
		 * 新手红包
		 */
		RedPack_NewUser: number;
		/**
		 * 话费券红包
		 */
		RedPack_Coupon: number;
		/**
		 * 充值红包
		 */
		RedPack_Recharge: number;
		/**
		 * 红包提现
		 */
		RedPack_Cash: number;
		/**
		 * 红包
		 */
		RedPack: number;
		/**
		 * 个人头像框
		 */
		Head_Box: number;
		/**
		 * 转盘
		 */
		turntable: number;
		/**
		 * 更多
		 */
		More: number;
		/**
		 * 明日礼包
		 */
		tomorrowgiftBag: number;

		GetType(): string { return 'table.TableRedPointConfig'; }
	}
}
