//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 时时彩表.xlsx SHEET: 时时彩基础数据
	 */
	export class TableshishicaiData {
		/**
		 * 序号
		 */
		shishicaiDataID: number;
		/**
		 * 赢家抽水
		 */
		winpump: number;
		/**
		 * 奖池抽水
		 */
		jackpotpump: number;
		/**
		 * 机器人携带下限
		 */
		robotcoinmin: number;
		/**
		 * 机器人携带上限
		 */
		robotcoinmax: number;
		/**
		 * 豹子阈值
		 */
		leopardmin: number;
		/**
		 * 不开豹子阈值
		 */
		notleopard: number[];
		/**
		 * 暗池阈值
		 */
		addjackpotmin: number;
		/**
		 * 奖池阈值
		 */
		jackpotmin: number;
		/**
		 * 轮数阈值
		 */
		roundmin: number;

		GetType(): string { return 'table.TableshishicaiData'; }
	}
}
