//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 新手红包.xlsx SHEET: 新手红包
	 */
	export class TableNoviceRed {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 物品概率
		 */
		probability: TableNoviceRed.ProbabilityItem[];

		GetType(): string { return 'table.TableNoviceRed'; }
	}
	export module TableNoviceRed {
		export class ProbabilityItem {
			value: number;
			reward: TableNoviceRed.ProbabilityItem.RewardItem;
		}
	}
	export module TableNoviceRed {
		export module ProbabilityItem {
			export class RewardItem {
				money: number;
				number: number;
				currencyType: number;
			}
		}
	}
}
