//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩金币大厅配置.xlsx SHEET: Sheet1 KEY: lobbyId
	 */
	export class TableCoinLobbyConfig {
		/**
		 * 大厅id
		 */
		lobbyId: number;
		/**
		 * vip话费券活动
		 */
		vipCouponActive: TableCoinLobbyConfig.VipCouponActiveItem[];
		/**
		 * 顺序弹窗配置
		 */
		seqPopups: TableCoinLobbyConfig.SeqPopupsItem[];
		/**
		 * 客服号
		 */
		customService: string;
		/**
		 * 魔窗下载地址
		 */
		downLoad: string;
		/**
		 * 机器人金币比例
		 */
		goldProportion: TableCoinLobbyConfig.GoldProportionItem[];
		/**
		 * 百宝箱任务
		 */
		treasureBoxTask: number[][];
		/**
		 * 百宝箱转盘奖励
		 */
		turnTreasureBox: number[];
		/**
		 * 币商ID
		 */
		moneyID: number[];
		/**
		 * 额外赠送倍率
		 */
		extra: number;
		/**
		 * 幸运翻翻翻
		 */
		luckTurnCard: number[];
		/**
		 * 在线奖励
		 */
		onlineReward: TableCoinLobbyConfig.OnlineRewardItem[];
		/**
		 * 喜从天降
		 */
		HappyfromdayDrop: number[];
		/**
		 * 新手红包
		 */
		NoviceRe: number[];
		/**
		 * 充值送礼
		 */
		rechargeG: number[];
		/**
		 * 默认头像
		 */
		dfheadPortrait: number[];
		/**
		 * 是否可换头像
		 */
		yncheadPortrait: number;

		GetType(): string { return 'table.TableCoinLobbyConfig'; }
	}
	export module TableCoinLobbyConfig {
		export class VipCouponActiveItem {
			vip: number;
			activeId: number;
		}
	}
	export module TableCoinLobbyConfig {
		export class SeqPopupsItem {
			popId: number;
			time: TableCoinLobbyConfig.SeqPopupsItem.TimeItem;
			mutex: number[];
		}
	}
	export module TableCoinLobbyConfig {
		export module SeqPopupsItem {
			export class TimeItem {
				st: number;
				et: number;
			}
		}
	}
	export module TableCoinLobbyConfig {
		export class GoldProportionItem {
			gameId: number;
			value: TableCoinLobbyConfig.GoldProportionItem.ValueItem[];
		}
	}
	export module TableCoinLobbyConfig {
		export module GoldProportionItem {
			export class ValueItem {
				range: number[];
				scale: number;
			}
		}
	}
	export module TableCoinLobbyConfig {
		export class OnlineRewardItem {
			onlineTime: number;
			reward: TableCoinLobbyConfig.OnlineRewardItem.RewardItem[];
		}
	}
	export module TableCoinLobbyConfig {
		export module OnlineRewardItem {
			export class RewardItem {
				goodsId: number;
				count: number;
			}
		}
	}
}
