//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩头像.xlsx SHEET: 默认头像
	 */
	export class Defaulthead {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 头像
		 */
		headPortrait: string;

		GetType(): string { return 'table.Defaulthead'; }
	}
}
