//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: gameList.xlsx SHEET: gameList
	 */
	export class gameList {
		id: number;
		gameId: number;
		gameDoc: string;
		gameName: string;
		gameDes: string;
		gameTag: string;
		gameTheme: string;
		gameResConfigUrl: string;
		gameResRoot: string;
		preLoad: string;
		gameCodeUrl: string;
		gameIconUrl: string;
		gameIconUrl2: string;
		gameIconUrl_gxpj: string;
		gameIconUrl_hpw: string;
		gameShareUrl: string;
		markIconUrl: string;
		selectScene: number;
		/**
		 * 包大小
		 */
		gameSize: string;
		stageScaleMode: string;
		wxgame: boolean;

		GetType(): string { return 'table.gameList'; }
	}
}
