//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 礼品券兑换表.xlsx SHEET: 礼品券兑换
	 */
	export class giftChange {
		/**
		 * 序号
		 */
		Id: number;
		/**
		 * 商品ID
		 */
		giftID: number;

		GetType(): string { return 'table.giftChange'; }
	}
}
