//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-新年活动开奖份额.xlsx SHEET: 邀请红包
	 */
	export class InviteEnvelope {
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 红包金额
		 */
		envelopeNumber: number;
		/**
		 * 概率
		 */
		prob: number;

		GetType(): string { return 'table.InviteEnvelope'; }
	}
}
