//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 机器人信息表.xlsx SHEET: 机器人
	 */
	export class Robotinfo {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 昵称
		 */
		name: string;
		/**
		 * 个性签名
		 */
		personsign: string;
		/**
		 * 充值金额
		 */
		paysum: number;
		/**
		 * 胜利局数
		 */
		win: number;
		/**
		 * 失败局数
		 */
		lose: number;

		GetType(): string { return 'table.Robotinfo'; }
	}
}
