//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-道具.xlsx SHEET: 道具
	 */
	export class TableGoodsConfig {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * ID
		 */
		goodId: number;
		/**
		 * 物品名称
		 */
		goodName: string;
		/**
		 * 物品类型
		 */
		goodType: number;
		/**
		 * 物品介绍
		 */
		goodDesc: string;
		/**
		 * 物品icon
		 */
		goodIcon: string;
		/**
		 * 显示按钮
		 */
		goodBotton: number[];
		/**
		 * 说明文字
		 */
		goodIntroduction: string;
		/**
		 * 显示
		 */
		isShow: number;
		/**
		 * 礼包配置
		 */
		giftGoods: TableGoodsConfig.GiftGoodsItem[];
		/**
		 * 每日赠送
		 */
		immediateGift: TableGoodsConfig.ImmediateGiftItem[];
		/**
		 * 出售价格
		 */
		price: number;
		/**
		 * 每日赠送金币
		 */
		giveGold: number;
		/**
		 * 有效时间
		 */
		effectiveTime: number;

		GetType(): string { return 'table.TableGoodsConfig'; }
	}
	export module TableGoodsConfig {
		export class GiftGoodsItem {
			goodId: number;
			goodNbr: number;
		}
	}
	export module TableGoodsConfig {
		export class ImmediateGiftItem {
			goodId: number;
			goodNbr: number;
		}
	}
}
