//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 转盘任务.xlsx SHEET: 任务
	 */
	export class TabletTask {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 次数
		 */
		frequency: number;
		/**
		 * 积分
		 */
		integral: number;
		/**
		 * 大厅ID
		 */
		lobbyID: number;
        /**
         * 任务类型
         */
		tasktype: number;
		GetType(): string { return 'table.TabletTask'; }
	}
}
