//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-创建房间选项.xlsx SHEET: 好牌网区域
	 */
	export class TableHaopaiAreaConfig {
		id: number;
		/**
		 * 市县
		 */
		province: string;
		/**
		 * 是否开启
		 */
		open: number;
		/**
		 * 首字母
		 */
		firstCharact: string;
		/**
		 * 游戏icon
		 */
		gameIcon: number[];
		/**
		 * 大厅ID
		 */
		lobbyId: number[];
		/**
		 * 定位ID
		 */
		districtId: number[];

		GetType(): string { return 'table.TableHaopaiAreaConfig'; }
	}
}
