//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-创建房间选项.xlsx SHEET: 区域
	 */
	export class TableLobbyAreaConfig {
		id: number;
		/**
		 * 市县
		 */
		province: string;
		/**
		 * 游戏
		 */
		areaGameList: number[];

		GetType(): string { return 'table.TableLobbyAreaConfig'; }
	}
}
