//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 转盘任务.xlsx SHEET: 转盘概率
	 */
	export class TableTurnPro {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 概率
		 */
		probability: number;
		/**
		 * 物品
		 */
		goods: TableTurnPro.GoodsItem[];

		GetType(): string { return 'table.TableTurnPro'; }
	}
	export module TableTurnPro {
		export class GoodsItem {
			goodId: number;
			goodNbr: number;
			goodProbability: number;
		}
	}
}
