//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 金币场保险箱.xlsx SHEET: 婺州娱乐保险箱
	 */
	export class TableGoldcoinbox {
		/**
		 * 大厅ID
		 */
		id: number;
		/**
		 * 最低金币
		 */
		minimumGold: TableGoldcoinbox.MinimumGoldItem;
		/**
		 * 封装金币
		 */
		encapsulationGold: TableGoldcoinbox.EncapsulationGoldItem[];
		/**
		 * 保险箱最低金币
		 */
		insuranceboxGold: TableGoldcoinbox.InsuranceboxGoldItem;

		GetType(): string { return 'table.TableGoldcoinbox'; }
	}
	export module TableGoldcoinbox {
		/**
		 * 最低金币
		 */
		export class MinimumGoldItem {
			goodId: number;
			goodNbr: number;
		}
	}
	export module TableGoldcoinbox {
		export class EncapsulationGoldItem {
			goodId: number;
			goodNbr: number;
		}
	}
	export module TableGoldcoinbox {
		/**
		 * 保险箱最低金币
		 */
		export class InsuranceboxGoldItem {
			goodId: number;
			goodNbr: number;
		}
	}
}
