//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a金猪闯关.xlsx SHEET: 金猪闯关
	 */
	export class TableGoldPig {
		/**
		 * 闯关类型
		 */
		goldpigType: number;
		/**
		 * 关数
		 */
		goldpigNumber: number;
		/**
		 * 闯关名称
		 */
		goldpigName: string;
		/**
		 * 游戏ID
		 */
		gameId: number;
		/**
		 * 游戏人数
		 */
		gameUserNbr: number;
		/**
		 * 排名奖励
		 */
		RankReward: TableGoldPig.RankRewardItem[][];
		/**
		 * 晋级人数
		 */
		riseRank: number[];
		/**
		 * 报名费用
		 */
		goldpigCost: TableGoldPig.GoldpigCostItem[];
		/**
		 * 开局人数
		 */
		MatchPlayerNumber: number;

		GetType(): string { return 'table.TableGoldPig'; }
	}
	export module TableGoldPig {
		export class RankRewardItem {
			goodId: number;
			goodNbr: number;
		}
	}
	export module TableGoldPig {
		export class GoldpigCostItem {
			goodId: number;
			goodNbr: number;
		}
	}
}
