//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 话费券兑现金.xlsx SHEET: 话费券兑现金
	 */
	export class TableCouponCouponCash {
		/**
		 * 现金数量
		 */
		cash: number;
		/**
		 * 兑换数量
		 */
		condition: number;

		GetType(): string { return 'table.TableCouponCouponCash'; }
	}
}
