//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 充值送话费券.xlsx SHEET: 充值送话费券
	 */
	export class TableRechargeGiveCallCoupon {
		/**
		 * 充值数量
		 */
		condition: number;
		/**
		 * 奖励数量
		 */
		number: number;
		/**
		 * 单位
		 */
		company: number;

		GetType(): string { return 'table.TableRechargeGiveCallCoupon'; }
	}
}
