//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-幸运大转盘.xlsx SHEET: 神秘宝箱
	 */
	export class TableTurnCumulative {
		/**
		 * 序列
		 */
		id: number;
		/**
		 * 物品
		 */
		name: string;
		/**
		 * ID
		 */
		goodId: number;
		/**
		 * 奖励
		 */
		giftGoods: TableTurnCumulative.GiftGoodsItem;
		/**
		 * 概率
		 */
		probability: number;

		GetType(): string { return 'table.TableTurnCumulative'; }
	}
	export module TableTurnCumulative {
		/**
		 * 奖励
		 */
		export class GiftGoodsItem {
			goodId: number;
			goodNbr: number;
		}
	}
}
