//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩vip特权活动.xlsx SHEET: 活动 KEY: id
	 */
	export class TableVipActiveConfig {
		id: number;
		/**
		 * 话费券奖励概率
		 */
		couponReward: TableVipActiveConfig.CouponRewardItem[];
		/**
		 * 好彩礼物概率
		 */
		giftProbability: number[];
		/**
		 * 消耗金币
		 */
		chips: number;
		/**
		 * 礼包名
		 */
		desc: string;
		/**
		 * 礼包类型
		 */
		typ: number;

		GetType(): string { return 'table.TableVipActiveConfig'; }
	}
	export module TableVipActiveConfig {
		export class CouponRewardItem {
			count: number;
			chance: number;
		}
	}
}
