//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 周边系统.xlsx SHEET: 签到 KEY: lobbyId
	 */
	export class TableSignIn {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 图标
		 */
		icon: number[];
		/**
		 * 签到奖励
		 */
		signReward: TableSignIn.SignRewardItem[];
		/**
		 * 累计奖励
		 */
		cumulativeReward: TableSignIn.CumulativeRewardItem[];
		/**
		 * 好彩累计话费券
		 */
		goodluckCallCoupon: TableSignIn.GoodluckCallCouponItem[];

		GetType(): string { return 'table.TableSignIn'; }
	}
	export module TableSignIn {
		export class SignRewardItem {
			dayNum: number;
			reward: TableSignIn.SignRewardItem.RewardItem;
		}
	}
	export module TableSignIn {
		export module SignRewardItem {
			export class RewardItem {
				goodsId: number;
				count: number;
			}
		}
	}
	export module TableSignIn {
		export class CumulativeRewardItem {
			cumulativeNum: number;
			reward: TableSignIn.CumulativeRewardItem.RewardItem;
		}
	}
	export module TableSignIn {
		export module CumulativeRewardItem {
			export class RewardItem {
				goodsId: number;
				count: number;
			}
		}
	}
	export module TableSignIn {
		export class GoodluckCallCouponItem {
			cumulativeNum: number;
			reward: TableSignIn.GoodluckCallCouponItem.RewardItem;
		}
	}
	export module TableSignIn {
		export module GoodluckCallCouponItem {
			export class RewardItem {
				goodsId: number;
				count: number;
			}
		}
	}
}
