//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 关键资源表.xlsx SHEET: 关键资源表
	 */
	export class TableCoreResources {
		/**
		 * 资源名
		 */
		resName: string;

		GetType(): string { return 'table.TableCoreResources'; }
	}
}
