//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: a房卡-创建房间选项.xlsx SHEET: 好牌网图标对应游戏
	 */
	export class TableHaopaiIconConfig {
		id: number;
		/**
		 * 名字
		 */
		name: string;
		/**
		 * 游戏
		 */
		game: number[];
		/**
		 * 游戏icon
		 */
		gameIcon: number[];

		GetType(): string { return 'table.TableHaopaiIconConfig'; }
	}
}
