//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 百宝箱每日任务表.xlsx SHEET: Sheet1 KEY: taskId
	 */
	export class TableTreasureBoxTask {
		/**
		 * 任务id
		 */
		taskId: number;
		/**
		 * 任务描述
		 */
		taskDesc: string;
		/**
		 * 任务进度
		 */
		total: number;
		/**
		 * 游戏id
		 */
		gameId: number;
		/**
		 * 场次id
		 */
		sceneId: number;
		/**
		 * 任务奖励
		 */
		lottery: TableTreasureBoxTask.LotteryItem;
		/**
		 * 麻将场次
		 */
		mahJong: number;

		GetType(): string { return 'table.TableTreasureBoxTask'; }
	}
	export module TableTreasureBoxTask {
		/**
		 * 任务奖励
		 */
		export class LotteryItem {
			lType: number;
			goodsId: number;
			goodsNum: number;
			rmb: number;
		}
	}
}
