//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 比赛配置.xlsx SHEET: 比赛配置 KEY: id
	 */
	export class TableMatchTypeList {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 比赛名称
		 */
		name: string;
		/**
		 * 所属大厅
		 */
		lobbyName: string;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 是否开启
		 */
		isStart: number;
		/**
		 * 线上线下
		 */
		o2o: number;
		/**
		 * 跑马灯
		 */
		broadcast: string;
		/**
		 * 人数
		 */
		userCount: number;
		/**
		 * 我的荣誉
		 */
		myHonor: TableMatchTypeList.MyHonorItem[];
		/**
		 * 补偿
		 */
		makeUp: TableMatchTypeList.MakeUpItem[];
		/**
		 * 报名时间
		 */
		enrollTime: string[];
		/**
		 * 游戏ID
		 */
		gameId: number;
		/**
		 * 比赛游戏
		 */
		gameName: string;
		/**
		 * 玩法选项
		 */
		playType: number[];
		/**
		 * 报名费用
		 */
		cost: TableMatchTypeList.CostItem[];
		/**
		 * 报名限制
		 */
		enrollLimit: number[];
		/**
		 * 后端跑马灯用
		 */
		serveUse: TableMatchTypeList.ServeUseItem[];
		/**
		 * 奖励前端展示
		 */
		show: TableMatchTypeList.ShowItem[];
		/**
		 * 比赛奖励
		 */
		lotteryInfo: TableMatchTypeList.LotteryInfoItem[];

		GetType(): string { return 'table.TableMatchTypeList'; }
	}
	export module TableMatchTypeList {
		export class MyHonorItem {
			id: number;
			name: string;
		}
	}
	export module TableMatchTypeList {
		export class MakeUpItem {
			id: number;
			num: number;
		}
	}
	export module TableMatchTypeList {
		export class CostItem {
			costId: number;
			count: number;
		}
	}
	export module TableMatchTypeList {
		export class ServeUseItem {
			rank: number;
			desc: string;
		}
	}
	export module TableMatchTypeList {
		export class ShowItem {
			rank: number;
			lottery: TableMatchTypeList.ShowItem.LotteryItem[];
		}
	}
	export module TableMatchTypeList {
		export module ShowItem {
			export class LotteryItem {
				goodsId: number;
				count: number;
			}
		}
	}
	export module TableMatchTypeList {
		export class LotteryInfoItem {
			rank: number;
			lottery: TableMatchTypeList.LotteryInfoItem.LotteryItem[];
		}
	}
	export module TableMatchTypeList {
		export module LotteryInfoItem {
			export class LotteryItem {
				goodsId: number;
				count: number;
			}
		}
	}
}
