//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩菜单.xlsx SHEET: 菜单
	 */
	export class TableMenu {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 菜单名称
		 */
		menuName: string;

		GetType(): string { return 'table.TableMenu'; }
	}
}
