//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 好彩真人vip礼物表.xlsx SHEET: Sheet1 KEY: lobbyId
	 */
	export class Tablehaocaivip {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 大厅ID
		 */
		lobbyId: number;
		/**
		 * 对应大厅名称
		 */
		lobbyName: string;
		vip1: number;
		vip2: number;
		vip3: number;
		vip4: number;
		vip5: number;
		vip6: number;
		vip7: number;
		vip8: number;
		vip9: number;
		/**
		 * 1元vip点
		 */
		vip: number;
		/**
		 * 每日赠送
		 */
		dayGift: Tablehaocaivip.DayGiftItem[];
		/**
		 * 救济金增加次数
		 */
		giftNum: Tablehaocaivip.GiftNumItem[];
		/**
		 * 任务奖品加成
		 */
		giftUp: Tablehaocaivip.GiftUpItem[];
		/**
		 * 专属昵称颜色
		 */
		nameColor: Tablehaocaivip.NameColorItem[];
		/**
		 * 签到奖励
		 */
		makeGift: Tablehaocaivip.MakeGiftItem[];
		/**
		 * 救济金金币加成
		 */
		giftcoinUp: Tablehaocaivip.GiftcoinUpItem[];
		/**
		 * 一次奖励
		 */
		firstGift: Tablehaocaivip.FirstGiftItem[];

		GetType(): string { return 'table.Tablehaocaivip'; }
	}
	export module Tablehaocaivip {
		export class DayGiftItem {
			id: number;
			num: number;
		}
	}
	export module Tablehaocaivip {
		export class GiftNumItem {
			id: number;
			num: number;
		}
	}
	export module Tablehaocaivip {
		export class GiftUpItem {
			id: number;
			num: number;
		}
	}
	export module Tablehaocaivip {
		export class NameColorItem {
			id: number;
			num: number;
		}
	}
	export module Tablehaocaivip {
		export class MakeGiftItem {
			id: number;
			num: number;
		}
	}
	export module Tablehaocaivip {
		export class GiftcoinUpItem {
			id: number;
			num: number;
		}
	}
	export module Tablehaocaivip {
		export class FirstGiftItem {
			dayNum: number;
			reward: Tablehaocaivip.FirstGiftItem.RewardItem;
		}
	}
	export module Tablehaocaivip {
		export module FirstGiftItem {
			export class RewardItem {
				coinNum: number;
				giftNum: number;
			}
		}
	}
}
