//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 限时优惠.xlsx SHEET: config
	 */
	export class TableLimitOfferConfig {
		id: number;
		/**
		 * 档位
		 */
		stalls: number;
		/**
		 * 优惠条件
		 */
		shopIds: number[];
		/**
		 * 开始时间
		 */
		startTime: string;
		/**
		 * 结束时间
		 */
		endTime: string;
		/**
		 * 活动时间
		 */
		actTime: number;

		GetType(): string { return 'table.TableLimitOfferConfig'; }
	}
}
