//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 字体.xlsx SHEET: 字体
	 */
	export class Typeface {
		id: number;
		/**
		 * 简体中文
		 */
		simplified: string;
		/**
		 * 繁体中文
		 */
		traditional: string;

		GetType(): string { return 'table.Typeface'; }
	}
}
