//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: bashi_plat.proto

module Cmd {
	/**
	 * 金币操作类型
	 */
	export enum GoldOperationType {
		/**
		 * 查询
		 */
		GoldOperationType_Query = 1,
		/**
		 * 转入
		 */
		GoldOperationType_InPut = 2,
		/**
		 * 转出
		 */
		GoldOperationType_OutPut = 3,
		/**
		 * 转入转出回执（客户端无视）
		 */
		GoldOperationType_Receipt = 4
	}
	/**
	 * 操作金币
	 */
	export class BSPlatOperationGoldCmd_CS {
		/**
		 * 操作类型
		 */
		optype: GoldOperationType;
		/**
		 * 操作的金币数量，查询时不填充
		 */
		gold: number;
		/**
		 * 当前银行金币数
		 */
		bankgold: number;
		/**
		 * 今日剩余可转出金币数
		 */
		withdrawlimit: number;
		/**
		 * 今日剩余可转入金币数
		 */
		depositlimit: number;
		/**
		 * 汇率
		 */
		exchangeRate: number;
		GetType(): string { return 'Cmd.BSPlatOperationGoldCmd_CS'; }
	}
}
