//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby_exchange.proto
/// <reference path="common.ts" />

module Cmd {
	/**
	 * 转账
	 */
	export class ExchangeItem {
		/**
		 * id	1代码钻石,2代表房卡, 3金币
		 */
		id: number;
		chips: number;
		GetType(): string { return 'Cmd.ExchangeItem'; }
	}
	/**
	 * 交易key生成
	 */
	export class ExchangeKeyGet_CS {
		/**
		 * 交易所需信息
		 */
		exchangeInfo: ExchangeItem;
		/**
		 * 生成的KEY
		 */
		exchangeKey: string;
		/**
		 * 剩余的筹码
		 */
		remainderChips: number;
		/**
		 * 返回码
		 */
		resultCode: number;
		GetType(): string { return 'Cmd.ExchangeKeyGet_CS'; }
	}
	/**
	 * 领取交易筹码
	 */
	export class ExchangeChipsReceive_CS {
		/**
		 * 领取key
		 */
		exchangeKey: string;
		/**
		 * 交易所需信息
		 */
		exchangeInfo: ExchangeItem;
		/**
		 * 剩余的筹码
		 */
		remainderChips: number;
		/**
		 * 返回码
		 */
		resultCode: number;
		GetType(): string { return 'Cmd.ExchangeChipsReceive_CS'; }
	}
	export class RedPaperInfo {
		/**
		 * 交易所需信息
		 */
		exchangeInfo: ExchangeItem;
		/**
		 * 领取key
		 */
		exchangeKey: string;
		/**
		 * 领取结果 0/1表示未领，已领
		 */
		bOk: number;
		/**
		 * 发送红包的名字
		 */
		sendUserName: string;
		/**
		 * 领取红包的名字
		 */
		recvUserName: string;
		/**
		 * 领取红包的时间
		 */
		recvTime: string;
		GetType(): string { return 'Cmd.RedPaperInfo'; }
	}
	/**
	 * 收发红包
	 */
	export class ExchangeRecordGet_CS {
		/**
		 * 返回码
		 */
		resultCode: number;
		/**
		 * 发出去的红包
		 */
		sendRecord: RedPaperInfo[];
		/**
		 * 收到的红包
		 */
		receiveRecord: RedPaperInfo[];
		GetType(): string { return 'Cmd.ExchangeRecordGet_CS'; }
	}
}
