//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby_club.proto
/// <reference path="common.ts" />
/// <reference path="poker_room.ts" />

module Cmd {
	/**
	 * 俱乐部数据更新
	 */
	export class UpdateInfoClubCmd_S {
		op: Cmd.UpdateOperator;
		/**
		 * 加入的俱乐部
		 */
		joinList: Cmd.ClubInfo[];
		/**
		 * 权限
		 */
		permission: Cmd.ClubInfo[];
		/**
		 * 最大加入数
		 */
		joinNumMax: number;
		/**
		 * 最大创建数
		 */
		createNumMax: number;
		GetType(): string { return 'Cmd.UpdateInfoClubCmd_S'; }
	}
	/**
	 * 获取我的俱乐部消息
	 */
	export class MyInfoUpdateClubCmd_C {
		clubList: number[];
		GetType(): string { return 'Cmd.MyInfoUpdateClubCmd_C'; }
	}
	/**
	 * 创建俱乐部请求
	 */
	export class CreateClubCmd_C {
		/**
		 * 俱乐部地址
		 */
		address: Cmd.Address;
		/**
		 * 俱乐部信息,有些不能上传的需要服务器验证
		 */
		club: Cmd.ClubInfo;
		cost: boolean;
		GetType(): string { return 'Cmd.CreateClubCmd_C'; }
	}
	export class CreateClubCmd_S {
		createNumMax: number;
		createNum: number;
		resultCode: number;
		cost: number;
		GetType(): string { return 'Cmd.CreateClubCmd_S'; }
	}
	/**
	 * 请求俱乐部信息
	 */
	export class RequestClubInfoClubCmd_C {
		clubId: number;
		GetType(): string { return 'Cmd.RequestClubInfoClubCmd_C'; }
	}
	/**
	 * 俱乐部数据更新
	 */
	export class ReturnClubInfoClubCmd_S {
		/**
		 * 俱乐部
		 */
		club: Cmd.ClubInfo;
		/**
		 * 申请列表
		 */
		joinList: Cmd.ClubInfo;
		GetType(): string { return 'Cmd.ReturnClubInfoClubCmd_S'; }
	}
	/**
	 * 解散俱乐部
	 */
	export class DissmisClubCmd_C {
		clubId: number;
		GetType(): string { return 'Cmd.DissmisClubCmd_C'; }
	}
	/**
	 * 解散俱乐部返回
	 */
	export class DissmisClubCmd_S {
		clubId: number;
		GetType(): string { return 'Cmd.DissmisClubCmd_S'; }
	}
	/**
	 * 退出俱乐部
	 */
	export class QuitClubCmd_C {
		clubId: number;
		GetType(): string { return 'Cmd.QuitClubCmd_C'; }
	}
	/**
	 * 退出俱乐部返回
	 */
	export class QuitClubCmd_S {
		clubId: number;
		uid: number;
		GetType(): string { return 'Cmd.QuitClubCmd_S'; }
	}
	/**
	 * 加入俱乐部请求
	 */
	export class JoinRequestClubCmd_C {
		clubId: number;
		msg: string;
		cost: boolean;
		GetType(): string { return 'Cmd.JoinRequestClubCmd_C'; }
	}
	/**
	 * 加入俱乐部回复
	 */
	export class JoinRequestClubCmd_S {
		joinNumMax: number;
		joinNum: number;
		resultCode: number;
		cost: number;
		GetType(): string { return 'Cmd.JoinRequestClubCmd_S'; }
	}
	/**
	 * 处理加入俱乐部请求
	 */
	export class JoinReturnClubCmd_C {
		clubId: number;
		/**
		 * 请求者uid
		 */
		applyUid: number;
		/**
		 * 处理结果
		 */
		yesOrNo: boolean;
		GetType(): string { return 'Cmd.JoinReturnClubCmd_C'; }
	}
	/**
	 * S-&gt;C 通知俱乐部成员信息
	 */
	export class MemberUpdateClubCmd_CS {
		clubId: number;
		memberList: Cmd.ClubInfo.Member[];
		op: Cmd.UpdateOperator;
		GetType(): string { return 'Cmd.MemberUpdateClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 查询俱乐部成员信息
	 *  S-&gt;C 回复俱乐部成员信息
	 */
	export class MemberQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		rows: Cmd.ClubInfo.Member[];
		sum: number;
		GetType(): string { return 'Cmd.MemberQueryClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 请求俱乐部某个成员信息
	 *  S-&gt;C 通知俱乐部某个成员信息
	 */
	export class MemberInfoGetClubCmd_CS {
		clubId: number;
		uid: number;
		member: Cmd.ClubInfo.Member;
		GetType(): string { return 'Cmd.MemberInfoGetClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 请求俱乐部某个成员金钱账单
	 *  S-&gt;C 返回俱乐部某个成员金钱账单
	 */
	export class MemberChipsStatementClubCmd_CS {
		filter: Cmd.FilterInfo;
		rows: Cmd.MoneyStatementInfo[];
		GetType(): string { return 'Cmd.MemberChipsStatementClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 请求俱乐部申请人信息
	 *  S-&gt;C 通知俱乐部申请人信息
	 */
	export class ApplicantUpdateClubCmd_CS {
		clubId: number;
		/**
		 * 申请人
		 */
		applicant: Cmd.ClubInfo.Member[];
		op: Cmd.UpdateOperator;
		filter: Cmd.FilterInfo;
		/**
		 * 总人数
		 */
		sum: number;
		GetType(): string { return 'Cmd.ApplicantUpdateClubCmd_CS'; }
	}
	/**
	 * 编辑俱乐部信息
	 */
	export class EditClubCmd_C {
		club: Cmd.ClubInfo;
		GetType(): string { return 'Cmd.EditClubCmd_C'; }
	}
	/**
	 *  C-&gt;S 搜索俱乐部请求
	 *  S-&gt;C 搜索俱乐部结果
	 */
	export class SearchClubCmd_CS {
		nameOrId: string;
		address: Cmd.Address;
		/**
		 * 查询数据
		 */
		rows: Cmd.ClubInfo[];
		filter: Cmd.FilterInfo;
		GetType(): string { return 'Cmd.SearchClubCmd_CS'; }
	}
	/**
	 * 设置俱乐部管理员
	 */
	export class PostUpdateClubCmd_CS {
		clubId: number;
		uid: number;
		post: Cmd.ClubInfo.Post;
		GetType(): string { return 'Cmd.PostUpdateClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 请求俱乐部牌局
	 *  S-&gt;C 返回俱乐部牌局
	 */
	export class GameUpdateClubCmd_CS {
		clubId: number;
		/**
		 * 截止时间点
		 */
		startAt: number;
		num: number;
		/**
		 * 牌局
		 */
		game: Cmd.TexasConfig[];
		op: Cmd.UpdateOperator;
		GetType(): string { return 'Cmd.GameUpdateClubCmd_CS'; }
	}
	/**
	 * 移除成员
	 */
	export class MemberRemoveClubCmd_C {
		clubId: number;
		uid: number;
		GetType(): string { return 'Cmd.MemberRemoveClubCmd_C'; }
	}
	/**
	 * 设置俱乐部权限
	 */
	export class PermissionUpdateClubCmd_C {
		op: Cmd.UpdateOperator;
		/**
		 * 职位权限
		 */
		postPermission: Cmd.ClubInfo.PostPermission;
		/**
		 * 俱乐部
		 */
		clubId: number;
		GetType(): string { return 'Cmd.PermissionUpdateClubCmd_C'; }
	}
	/**
	 * 充值基金
	 */
	export class FundRechargeClubCmd_C {
		clubId: number;
		/**
		 * 兑换的钻石数
		 */
		diamond: number;
		GetType(): string { return 'Cmd.FundRechargeClubCmd_C'; }
	}
	/**
	 * 基金分发
	 */
	export class FundDistributeClubCmd_C {
		/**
		 * 俱乐部ID
		 */
		clubId: number;
		/**
		 * 资金类型 1：基金，2：钻石
		 */
		type: number;
		/**
		 * 发放数量
		 */
		num: number;
		/**
		 * 目标玩家
		 */
		toId: number;
		inClub: boolean;
		/**
		 * 发放的目标
		 */
		uids: number[];
		GetType(): string { return 'Cmd.FundDistributeClubCmd_C'; }
	}
	/**
	 * 基金数据更新
	 */
	export class FundInfoUpdateCmd_S {
		clubId: number;
		/**
		 * 剩余数
		 */
		left: number;
		GetType(): string { return 'Cmd.FundInfoUpdateCmd_S'; }
	}
	/**
	 *  C-&gt;S 转账请求
	 *  S-&gt;C 新的转账请求通知
	 */
	export class TransitMoneyClubCmd_CS {
		clubId: number;
		num: number;
		/**
		 * true 转进俱乐部 false 转出俱乐部
		 */
		inOrOut: boolean;
		GetType(): string { return 'Cmd.TransitMoneyClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 请求转账列表
	 *  S-&gt;C 返回转账列表
	 */
	export class TransitMoneyQueryClubCmd_CS {
		clubId: number;
		filter: Cmd.FilterInfo;
		rows: Cmd.ClubInfo.Transition[];
		sum: number;
		GetType(): string { return 'Cmd.TransitMoneyQueryClubCmd_CS'; }
	}
	/**
	 * 转账处理
	 */
	export class TransitMoneyDealClubCmd_CS {
		id: number;
		/**
		 * 0 未处理 1 同意 2 不同意 5 撤销
		 */
		deal: number;
		clubId: number;
		/**
		 * 资金类型 1：基金，2：钻石
		 */
		type: number;
		GetType(): string { return 'Cmd.TransitMoneyDealClubCmd_CS'; }
	}
	/**
	 * 红点提示
	 */
	export class TipsUpdateClubCmd_CS {
		clubId: number;
		tips: Cmd.MsgType[];
		op: Cmd.UpdateOperator;
		GetType(): string { return 'Cmd.TipsUpdateClubCmd_CS'; }
	}
	/**
	 * 创建者信息更新
	 */
	export class FounderInfoUpdateClubCmd_S {
		clubId: number;
		founderInfo: Cmd.UserBaseInfo;
		GetType(): string { return 'Cmd.FounderInfoUpdateClubCmd_S'; }
	}
	/**
	 * 货币兑换
	 */
	export class ExchangeMoneyClubCmd_CS {
		shopId: number;
		GetType(): string { return 'Cmd.ExchangeMoneyClubCmd_CS'; }
	}
	/**
	 * 升级俱乐部
	 */
	export class UpgradeClubCmd_C {
		clubId: number;
		GetType(): string { return 'Cmd.UpgradeClubCmd_C'; }
	}
	/**
	 * 牌局生成器
	 */
	export class RoomGenerator {
		id: number;
		config: Cmd.TexasConfig;
		enable: boolean;
		num: number;
		createdAt: number;
		name: string;
		GetType(): string { return 'Cmd.RoomGenerator'; }
	}
	/**
	 *  C-&gt;S 牌局生成器操作请求
	 *  S-&gt;C 牌局生成器操作通知
	 */
	export class RoomGeneratorUpdateClubCmd_CS {
		clubId: number;
		op: Cmd.UpdateOperator;
		rows: RoomGenerator[];
		GetType(): string { return 'Cmd.RoomGeneratorUpdateClubCmd_CS'; }
	}
	/**
	 * C-&gt;S 获取自己代理下级代理关系线
	 */
	export class AgentRelationLineQueryClubCmd_CS {
		clubId: number;
		uid: number;
		line: Cmd.ClubInfo.Member[];
		GetType(): string { return 'Cmd.AgentRelationLineQueryClubCmd_CS'; }
	}
	/**
	 * 查询玩家可重设的上级
	 */
	export class AgentAvailableUplineQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		rows: Cmd.ClubInfo.Member[];
		GetType(): string { return 'Cmd.AgentAvailableUplineQueryClubCmd_CS'; }
	}
	/**
	 * 设置代理上线
	 */
	export class AgentUplineUpdateClubCmd_C {
		clubId: number;
		uid: number;
		upline: number;
		GetType(): string { return 'Cmd.AgentUplineUpdateClubCmd_C'; }
	}
	/**
	 * 查询自己的下线成员列表
	 */
	export class AgentAvailableGiveMemberQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		rows: Cmd.ClubInfo.Member[];
		GetType(): string { return 'Cmd.AgentAvailableGiveMemberQueryClubCmd_CS'; }
	}
	/**
	 * 给代理分配成员
	 */
	export class AgentGiveMemberClubCmd_C {
		clubId: number;
		uid: number;
		/**
		 * 新分配的玩家
		 */
		giveList: number[];
		/**
		 * 拿回的玩家
		 */
		fetchList: number[];
		GetType(): string { return 'Cmd.AgentGiveMemberClubCmd_C'; }
	}
	/**
	 *  C-&gt;S 请求修改代理信誉值
	 *  S-&gt;C 修改代理信誉值通知
	 */
	export class AgentCreditChangeClubCmd_CS {
		clubId: number;
		uid: number;
		value: number;
		GetType(): string { return 'Cmd.AgentCreditChangeClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 代理信誉值记录查询
	 *  S-&gt;C 代理信誉值记录回复
	 */
	export class AgentCreditChangeQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		rows: AgentCreditChangeQueryClubCmd_CS.CreditChangeInfo[];
		GetType(): string { return 'Cmd.AgentCreditChangeQueryClubCmd_CS'; }
	}
	export module AgentCreditChangeQueryClubCmd_CS {
		export class CreditChangeInfo {
			id: number;
			createdAt: number;
			num: number;
			uplineUser: Cmd.UserBaseInfo;
			downUser: Cmd.UserBaseInfo;
			GetType(): string { return 'Cmd.AgentCreditChangeQueryClubCmd_CS.CreditChangeInfo'; }
		}
	}
	/**
	 * 代理房间数据查询
	 */
	export class AgentStatisticsRoomQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		rows: ClubRoomData[];
		sum: Cmd.StatisticsRoundData;
		isSum: boolean;
		GetType(): string { return 'Cmd.AgentStatisticsRoomQueryClubCmd_CS'; }
	}
	/**
	 * 代理单个房间详情查询
	 */
	export class AgentStatisticsRoomCheckClubCmd_CS {
		filter: Cmd.FilterInfo;
		roomdata: Cmd.TexasConfig;
		rows: Cmd.StatisticsRoundData[];
		sum: Cmd.StatisticsRoundData;
		GetType(): string { return 'Cmd.AgentStatisticsRoomCheckClubCmd_CS'; }
	}
	export class UnionData {
		unionId: number;
		name: string;
		headurl: string;
		fund: number;
		createdAt: number;
		memberLimit: number;
		clubId: number;
		founder: number;
		donatedata: Cmd.DonateData;
		memberList: Cmd.ClubInfo[];
		GetType(): string { return 'Cmd.UnionData'; }
	}
	export class UnionMemberData {
		unionId: number;
		clubId: number;
		credit: number;
		createdAt: number;
		club: Cmd.ClubInfo;
		id: number;
		GetType(): string { return 'Cmd.UnionMemberData'; }
	}
	/**
	 *  C-&gt;S 创建联盟请求
	 *  S-&gt;S 创建联盟成功
	 */
	export class UnionCreateClubCmd_CS {
		clubId: number;
		name: string;
		GetType(): string { return 'Cmd.UnionCreateClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 加入联盟请求
	 *  S-&gt;C 加入联盟结果
	 */
	export class UnionJoinRequestClubCmd_CS {
		uniondata: UnionData;
		result: number;
		GetType(): string { return 'Cmd.UnionJoinRequestClubCmd_CS'; }
	}
	/**
	 * 加入联盟请求处理
	 */
	export class UnionJoinReturnClubCmd_C {
		unionId: number;
		/**
		 * 请求者uid
		 */
		clubId: number;
		/**
		 * 处理结果
		 */
		yesOrNo: boolean;
		GetType(): string { return 'Cmd.UnionJoinReturnClubCmd_C'; }
	}
	/**
	 * 编辑
	 */
	export class UnionEditClubCmd_CS {
		uniondata: UnionData;
		GetType(): string { return 'Cmd.UnionEditClubCmd_CS'; }
	}
	/**
	 * 解散
	 */
	export class UnionDismissClubCmd_C {
		unionId: number;
		GetType(): string { return 'Cmd.UnionDismissClubCmd_C'; }
	}
	/**
	 * 联盟更新
	 */
	export class UnionUpdateClubCmd_CS {
		clubId: number;
		op: Cmd.UpdateOperator;
		rows: UnionData[];
		GetType(): string { return 'Cmd.UnionUpdateClubCmd_CS'; }
	}
	/**
	 * 退出
	 */
	export class UnionQuitClubCmd_C {
		unionId: number;
		clubId: number;
		GetType(): string { return 'Cmd.UnionQuitClubCmd_C'; }
	}
	/**
	 * 基金充值
	 */
	export class UnionFundRechargeClubCmd_C {
		unionId: number;
		num: number;
		GetType(): string { return 'Cmd.UnionFundRechargeClubCmd_C'; }
	}
	/**
	 * 基金分发
	 */
	export class UnionFundDistributeClubCmd_C {
		unionId: number;
		num: number;
		clubList: number[];
		GetType(): string { return 'Cmd.UnionFundDistributeClubCmd_C'; }
	}
	/**
	 * 基金记录查询
	 */
	export class UnionFundDistributeQueryClubCmd_CS {
		unionId: number;
		filter: Cmd.FilterInfo;
		rows: UnionMemberData[];
		GetType(): string { return 'Cmd.UnionFundDistributeQueryClubCmd_CS'; }
	}
	/**
	 * 基金修改
	 */
	export class UnionFundInfoUpdateCmd_S {
		unionId: number;
		left: number;
		GetType(): string { return 'Cmd.UnionFundInfoUpdateCmd_S'; }
	}
	/**
	 *  C-&gt;S 请求俱乐部申请人信息
	 *  S-&gt;C 通知俱乐部申请人信息
	 */
	export class UnionApplicantUpdateClubCmd_CS {
		unionId: number;
		/**
		 * 申请人
		 */
		applicant: UnionMemberData[];
		op: Cmd.UpdateOperator;
		filter: Cmd.FilterInfo;
		sum: number;
		GetType(): string { return 'Cmd.UnionApplicantUpdateClubCmd_CS'; }
	}
	/**
	 *  C-&gt;S 请求俱乐部成员信息
	 *  S-&gt;C 通知俱乐部成员信息
	 */
	export class UnionMemberUpdateClubCmd_CS {
		unionId: number;
		memberList: UnionMemberData[];
		op: Cmd.UpdateOperator;
		GetType(): string { return 'Cmd.UnionMemberUpdateClubCmd_CS'; }
	}
	/**
	 * 移除成员
	 */
	export class UnionMemberRemoveClubCmd_C {
		unionId: number;
		clubId: number;
		GetType(): string { return 'Cmd.UnionMemberRemoveClubCmd_C'; }
	}
	/**
	 * 联盟牌局数据总和查询
	 */
	export class UnionStatisticsSumQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		statistics: Cmd.StatisticsRoundData;
		GetType(): string { return 'Cmd.UnionStatisticsSumQueryClubCmd_CS'; }
	}
	export class ClubRoomData {
		roomdata: Cmd.TexasConfig;
		result: Cmd.StatisticsRoundData;
		GetType(): string { return 'Cmd.ClubRoomData'; }
	}
	/**
	 * 联盟房间数据查询
	 */
	export class UnionStatisticsRoomQueryClubCmd_CS {
		filter: Cmd.FilterInfo;
		/**
		 * 1 买入 2 保险 3 捐献金
		 */
		which: number;
		rows: ClubRoomData[];
		GetType(): string { return 'Cmd.UnionStatisticsRoomQueryClubCmd_CS'; }
	}
	/**
	 * 俱乐部索取
	 */
	export class FundClaimClubCmd_C {
		/**
		 * 俱乐部ID
		 */
		clubId: number;
		/**
		 * 资金类型 1：基金，2：钻石
		 */
		type: number;
		/**
		 * 索取
		 */
		num: number;
		/**
		 * 目标玩家
		 */
		toId: number;
		inClub: boolean;
		/**
		 * 索取的目标
		 */
		uids: number[];
		GetType(): string { return 'Cmd.FundClaimClubCmd_C'; }
	}
}
